# Generated by Django 5.2.10 on 2026-02-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(help_text="Short identifier for URL matching (e.g., 'mit', 'stanford')", max_length=100, unique=True)),
                ('location_country', models.CharField(max_length=100)),
                ('location_state', models.CharField(blank=True, max_length=100)),
                ('location_city', models.CharField(max_length=100)),
                ('campus_type', models.CharField(choices=[('urban', 'Urban'), ('suburban', 'Suburban'), ('rural', 'Rural')], max_length=50)),
                ('institution_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('public_private', 'Public/Private')], max_length=50)),
                ('setting', models.CharField(choices=[('small', 'Small (< 5,000)'), ('medium', 'Medium (5,000 - 15,000)'), ('large', 'Large (> 15,000)')], max_length=50)),
                ('undergraduate_enrollment', models.IntegerField()),
                ('acceptance_rate', models.FloatField(help_text='Acceptance rate as percentage (e.g., 5.2 for 5.2%)')),
                ('acceptance_rate_2023', models.FloatField(blank=True, null=True)),
                ('sat_required', models.BooleanField(default=True)),
                ('sat_optional', models.BooleanField(default=False)),
                ('sat_25th', models.IntegerField(blank=True, help_text='25th percentile SAT score', null=True)),
                ('sat_75th', models.IntegerField(blank=True, help_text='75th percentile SAT score', null=True)),
                ('sat_avg', models.IntegerField(blank=True, help_text='Average SAT score', null=True)),
                ('act_required', models.BooleanField(default=True)),
                ('act_optional', models.BooleanField(default=False)),
                ('act_25th', models.IntegerField(blank=True, help_text='25th percentile ACT score', null=True)),
                ('act_75th', models.IntegerField(blank=True, help_text='75th percentile ACT score', null=True)),
                ('act_avg', models.FloatField(blank=True, help_text='Average ACT score', null=True)),
                ('early_decision_deadline', models.DateField(blank=True, null=True)),
                ('early_action_deadline', models.DateField(blank=True, null=True)),
                ('regular_decision_deadline', models.DateField()),
                ('rolling_admissions', models.BooleanField(default=False)),
                ('popular_majors', models.JSONField(default=list, help_text='List of popular majors')),
                ('all_majors', models.JSONField(default=list, help_text='Comprehensive list of all majors offered')),
                ('all_majors_normalized', models.JSONField(default=list, help_text='Lowercase version of majors for case-insensitive matching')),
                ('strength_programs', models.JSONField(default=list, help_text='List of especially strong programs/departments')),
                ('strength_programs_normalized', models.JSONField(default=list, help_text='Lowercase version of strength programs for matching')),
                ('tuition_in_state', models.IntegerField(help_text='In-state tuition per year')),
                ('tuition_out_of_state', models.IntegerField(help_text='Out-of-state tuition per year')),
                ('room_board', models.IntegerField(help_text='Room and board per year')),
                ('total_cost_per_year', models.IntegerField(help_text='Total cost per year')),
                ('need_based_aid', models.BooleanField(default=False, help_text='Offers need-based financial aid')),
                ('need_blind', models.BooleanField(default=False, help_text='Need-blind admissions (does not consider ability to pay)')),
                ('need_aware', models.BooleanField(default=False, help_text='Need-aware admissions (considers ability to pay)')),
                ('merit_aid_offered', models.BooleanField(default=False, help_text='Offers merit-based scholarships')),
                ('avg_merit_award', models.IntegerField(blank=True, help_text='Average merit scholarship amount', null=True)),
                ('full_ride_available', models.BooleanField(default=False, help_text='Full-ride scholarships available')),
                ('international_aid', models.BooleanField(default=False, help_text='Offers financial aid to international students')),
                ('international_aid_details', models.TextField(blank=True, help_text='Details about international student aid policies')),
                ('aid_verified', models.BooleanField(default=False, help_text='Aid information has been verified')),
                ('aid_verified_date', models.DateField(blank=True, null=True)),
                ('aid_source', models.CharField(blank=True, help_text='Source of aid data (e.g., common_data_set, website)', max_length=100)),
                ('us_news_ranking', models.IntegerField(blank=True, null=True)),
                ('research_intensity', models.CharField(choices=[('very_high', 'Very High (R1)'), ('high', 'High (R2)'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('co_op_programs', models.BooleanField(default=False, help_text='Offers cooperative education programs')),
                ('honors_program', models.BooleanField(default=False)),
                ('first_year_seminars', models.BooleanField(default=False)),
                ('employed_within_6_months', models.FloatField(blank=True, help_text='Percentage employed within 6 months (as percentage, e.g., 95.0)', null=True)),
                ('avg_starting_salary', models.IntegerField(blank=True, help_text='Average starting salary', null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.CharField(default='manual', help_text='ipeds, common_data_set, manual', max_length=100)),
                ('last_verified', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['short_name'], name='university__short_n_8892a6_idx'), models.Index(fields=['location_country'], name='university__locatio_0b0b61_idx'), models.Index(fields=['acceptance_rate'], name='university__accepta_e71f2e_idx'), models.Index(fields=['need_blind', 'international_aid'], name='university__need_bl_93f298_idx')],
            },
        ),
    ]
