# Generated by Django 5.2.10 on 2026-02-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='campus_photo_url',
            field=models.URLField(blank=True, help_text='URL to campus photo (Wikipedia or official source)', max_length=500),
        ),
        migrations.AddField(
            model_name='university',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL to university logo (Wikipedia or official source)', max_length=500),
        ),
    ]
