# Generated by Django 5.2.10 on 2026-02-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_database', '0002_university_campus_photo_url_university_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='education_requirements',
            field=models.JSONField(blank=True, default=dict, help_text="University-specific education requirements: {min_gpa: 3.5, required_tests: ['SAT'], foundation_accepted: true, special_notes: '...'}"),
        ),
        migrations.CreateModel(
            name='CountryRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, unique=True)),
                ('education_system_required', models.CharField(blank=True, help_text="Minimum education system: '12-year', 'IB', 'A-Level', '13-year', etc.", max_length=100)),
                ('foundation_required', models.BooleanField(default=False, help_text='Whether foundation year is required for students with insufficient education')),
                ('foundation_duration', models.CharField(blank=True, help_text="Duration of foundation: '1 year', '2 semesters', '9 months', etc.", max_length=100)),
                ('alternative_paths', models.TextField(blank=True, help_text="Alternative options if foundation not viable: 'Study in 12-year system country first', etc.")),
                ('language_requirement', models.CharField(blank=True, help_text="Minimum language scores: 'IELTS 6.5', 'TOEFL 80', 'Italian B2', etc.", max_length=100)),
                ('special_rules', models.TextField(blank=True, help_text="Special procedures: 'Legal translation required', 'Consulate verification', 'UCAS system', etc.")),
                ('application_system', models.CharField(blank=True, help_text="Application platform: 'Common App', 'UCAS', 'Studielink', 'Direct', etc.", max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about admission process')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country Requirement',
                'verbose_name_plural': 'Country Requirements',
                'ordering': ['country'],
                'indexes': [models.Index(fields=['country'], name='university__country_072efc_idx'), models.Index(fields=['foundation_required'], name='university__foundat_0c15d2_idx')],
            },
        ),
    ]
