# Generated by Django 5.2.10 on 2026-02-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_database', '0003_university_education_requirements_countryrequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryrequirement',
            name='default_essay_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='countryrequirement',
            name='default_language_test',
            field=models.CharField(choices=[('ielts', 'IELTS'), ('toefl', 'TOEFL'), ('none', 'None')], default='ielts', max_length=20),
        ),
        migrations.AddField(
            model_name='countryrequirement',
            name='default_min_ielts',
            field=models.FloatField(default=6.5),
        ),
        migrations.AddField(
            model_name='countryrequirement',
            name='default_num_recommendations',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='countryrequirement',
            name='foundation_available',
            field=models.BooleanField(default=False, help_text='Foundation programs available in this country'),
        ),
        migrations.AddField(
            model_name='countryrequirement',
            name='foundation_duration_years',
            field=models.FloatField(default=1.0, help_text='Typical foundation program duration'),
        ),
        migrations.AddField(
            model_name='countryrequirement',
            name='foundation_min_years',
            field=models.IntegerField(blank=True, help_text='If student has >= this many years, foundation is an option', null=True),
        ),
        migrations.AddField(
            model_name='countryrequirement',
            name='min_years_of_education',
            field=models.IntegerField(default=12, help_text='Minimum years of education required'),
        ),
        migrations.AddField(
            model_name='university',
            name='application_portal',
            field=models.CharField(blank=True, choices=[('common_app', 'Common App'), ('ucas', 'UCAS'), ('own_portal', 'University Own Portal'), ('direct', 'Direct Application'), ('other', 'Other')], default='', help_text='Application portal type', max_length=50),
        ),
        migrations.AddField(
            model_name='university',
            name='application_portal_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='early_deadline',
            field=models.DateField(blank=True, help_text='Early action/decision deadline', null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='essay_prompt',
            field=models.TextField(blank=True, help_text='Essay prompt for this university'),
        ),
        migrations.AddField(
            model_name='university',
            name='essay_required',
            field=models.BooleanField(blank=True, help_text='Null = use country default', null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='foundation_available',
            field=models.BooleanField(blank=True, help_text='Foundation program available. Null = use country default.', null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='foundation_min_years',
            field=models.IntegerField(blank=True, help_text='Minimum education years for foundation eligibility. Null = use country default.', null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='ielts_validity_years',
            field=models.IntegerField(default=2, help_text='How many years IELTS score is valid'),
        ),
        migrations.AddField(
            model_name='university',
            name='language_requirement_type',
            field=models.CharField(blank=True, choices=[('ielts', 'IELTS'), ('toefl', 'TOEFL'), ('duolingo', 'Duolingo'), ('none', 'None')], default='', help_text='Primary language test type', max_length=20),
        ),
        migrations.AddField(
            model_name='university',
            name='min_ielts_listening',
            field=models.FloatField(blank=True, help_text='Minimum IELTS Listening score', null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='min_ielts_reading',
            field=models.FloatField(blank=True, help_text='Minimum IELTS Reading score', null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='min_ielts_score',
            field=models.FloatField(blank=True, help_text='Minimum IELTS score required', null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='min_ielts_speaking',
            field=models.FloatField(blank=True, help_text='Minimum IELTS Speaking score', null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='min_ielts_writing',
            field=models.FloatField(blank=True, help_text='Minimum IELTS Writing score', null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='min_years_of_education',
            field=models.IntegerField(default=12, help_text='Minimum years of education required'),
        ),
        migrations.AddField(
            model_name='university',
            name='num_recommendations',
            field=models.IntegerField(blank=True, help_text='Number of recommendation letters required. Null = use country default.', null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='regular_deadline',
            field=models.DateField(blank=True, help_text='Primary application deadline', null=True),
        ),
        migrations.AlterField(
            model_name='countryrequirement',
            name='education_system_required',
            field=models.CharField(blank=True, help_text="Minimum education system: '12-year', 'IB', 'A-Level', '13-year', etc. (LEGACY)", max_length=100),
        ),
    ]
