# Generated by Django 5.1.5 on 2025-10-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_current_streak_user_last_activity_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Русский')], default='en', max_length=5),
        ),
    ]
