# Generated by Django 5.1.5 on 2025-10-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_push_enabled_user_push_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', help_text="User's timezone for accurate time interpretation", max_length=63),
        ),
    ]
