# Generated by Django 5.1.5 on 2025-11-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='companies_worked',
            field=models.JSONField(blank=True, default=list, help_text='["Google", "Startup XYZ"]'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_role',
            field=models.CharField(blank=True, help_text='Current job title', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='field_of_study',
            field=models.CharField(blank=True, help_text='e.g., Computer Science, Business', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fitness_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], help_text='Self-assessed fitness level', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GPA on 4.0 scale', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gym_access',
            field=models.BooleanField(blank=True, help_text='Has access to gym equipment', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='injuries_limitations',
            field=models.JSONField(blank=True, default=list, help_text='["Knee injury", "Lower back pain"]'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_performance_analysis',
            field=models.DateTimeField(blank=True, help_text='When performance was last analyzed', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='performance_insights',
            field=models.JSONField(blank=True, default=dict, help_text='AI-generated patterns: optimal schedule, blockers, strengths'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prior_education',
            field=models.JSONField(blank=True, default=list, help_text='[{"degree": "BSc", "institution": "KazNU", "year": 2023}]'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referral_network_size',
            field=models.IntegerField(blank=True, help_text='Number of people who could refer you', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text='["Python", "React", "Project Management"]'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='test_scores',
            field=models.JSONField(blank=True, default=dict, help_text='{"IELTS": 7.0, "TOEFL": 100, "GRE": 320, "GMAT": 700}'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='workout_history',
            field=models.JSONField(blank=True, default=dict, help_text='{"frequency": "3x/week", "duration": "45min"}'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='years_of_experience',
            field=models.IntegerField(blank=True, help_text='Total years of professional experience', null=True),
        ),
    ]
