# Generated by Django 5.1.5 on 2025-11-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprofile_companies_worked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='intervention_history',
            field=models.JSONField(blank=True, default=list, help_text='[{"date": "2025-11-06", "type": "planb_switch", "accepted": true}]'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_intervention_at',
            field=models.DateTimeField(blank=True, help_text='When AdaptiveCoach last intervened', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_intervention_type',
            field=models.CharField(blank=True, help_text='planb_switch | workload_reduction | blocker_resolution | etc.', max_length=50),
        ),
    ]
