# Generated by Django 5.1.5 on 2025-11-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userprofile_intervention_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='career_specialization',
            field=models.CharField(blank=True, help_text='e.g., Backend Engineer, UX Designer, Product Manager', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_company',
            field=models.CharField(blank=True, help_text='Current employer name', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='design_discipline',
            field=models.CharField(blank=True, help_text='e.g., UX Designer, UI Designer, Product Designer', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='design_specialization',
            field=models.CharField(blank=True, help_text='e.g., B2B SaaS, Mobile Apps, E-commerce', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='design_tools',
            field=models.JSONField(blank=True, default=dict, help_text='{"design": ["Figma", "Sketch"], "prototyping": ["Protopie"], "research": ["Maze"]}'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('entry', 'Entry-level (0-1 years)'), ('junior', 'Junior (1-2 years)'), ('mid', 'Mid-level (3-5 years)'), ('senior', 'Senior (5-8 years)'), ('staff_plus', 'Staff+ (8+ years)')], help_text='Structured experience level', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notable_projects',
            field=models.JSONField(blank=True, default=list, help_text='[{"title": "Built real-time chat", "impact": "Handled 10k users"}]'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='portfolio_quality',
            field=models.CharField(blank=True, choices=[('none', 'No portfolio yet'), ('basic', 'Basic portfolio (3-5 projects)'), ('strong', 'Strong portfolio (5-10 case studies)'), ('award_winning', 'Award-winning portfolio')], help_text='Self-assessed portfolio quality', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_company_types',
            field=models.JSONField(blank=True, default=list, help_text='["Startups", "FAANG", "Finance", "Remote-first"]'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tech_stack',
            field=models.JSONField(blank=True, default=dict, help_text='{"languages": ["Python", "JavaScript"], "frameworks": ["React", "Node.js"], "databases": ["PostgreSQL"], "cloud": ["AWS", "Docker"]}'),
        ),
    ]
