# Generated by Django 5.1.5 on 2025-11-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userprofile_career_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='budget',
            field=models.CharField(blank=True, help_text="Budget per year (e.g., '$15,000') from conversational onboarding", max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_education',
            field=models.CharField(blank=True, help_text='Current degree and university from conversational onboarding', max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='degree_level',
            field=models.CharField(blank=True, help_text='bachelor, master, phd, bootcamp from conversational onboarding', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='equipment',
            field=models.JSONField(blank=True, default=list, help_text='["dumbbells", "yoga mat"] from conversational onboarding'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fitness_goal_type',
            field=models.CharField(blank=True, help_text='lose_weight, build_muscle, run_marathon, etc. from conversational onboarding', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='injuries',
            field=models.TextField(blank=True, help_text='Text description of injuries from conversational onboarding'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notable_achievements',
            field=models.JSONField(blank=True, default=list, help_text='["Built system handling 50k req/sec", "Led team of 5"] from conversational onboarding'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='research_interests',
            field=models.TextField(blank=True, help_text='Research interests for grad programs from conversational onboarding'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_companies',
            field=models.JSONField(blank=True, default=list, help_text='["Startups", "FAANG"] from conversational onboarding'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_country',
            field=models.CharField(blank=True, help_text='Target country for studying from conversational onboarding', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_role',
            field=models.CharField(blank=True, help_text='Target role from conversational onboarding', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_schools',
            field=models.JSONField(blank=True, default=list, help_text='["University of Edinburgh", "UCF"] from conversational onboarding'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timeline',
            field=models.CharField(blank=True, help_text="Timeline/deadline from conversational onboarding (e.g., '6 months', 'Fall 2026')", max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='years_experience',
            field=models.IntegerField(blank=True, help_text='Alias for years_of_experience for conversational onboarding compatibility', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tech_stack',
            field=models.JSONField(blank=True, default=dict, help_text='Can be dict {"languages": [...]} OR list ["Python", "Django"] from conversational onboarding'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='test_scores',
            field=models.JSONField(blank=True, default=dict, help_text='{"IELTS": 7.0, "TOEFL": 100, "GRE": 320, "GMAT": 700} or {"ielts": 7.0} from conversational'),
        ),
    ]
