# Generated by Django 5.1.5 on 2025-11-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_userprofile_coding_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='achievement_details',
            field=models.TextField(blank=True, help_text="Details with metrics/impact. Example: 'Won national coding olympiad 2023' or 'Built system handling 50k users'"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_notable_achievements',
            field=models.BooleanField(default=False, help_text='User has impressive achievements: awards, competitions, publications, impactful projects'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_research_background',
            field=models.BooleanField(default=False, help_text='User has research experience: papers, publications, working with professors'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_startup_background',
            field=models.BooleanField(default=False, help_text='User has founded/built startup, business, or product with users'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='impressive_projects',
            field=models.JSONField(blank=True, default=list, help_text='List of impressive projects with metrics. Example: ["E-commerce site with $50k revenue", "Open-source library with 2k stars"]'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='research_details',
            field=models.TextField(blank=True, help_text="Details: field, publications, professors, lab work. Example: 'ML research with Prof. Smith, published at EMNLP 2024'"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='startup_details',
            field=models.TextField(blank=True, help_text="Details: what it does, users/customers, revenue, funding, role. Example: 'Language learning app, 10k users, built in high school'"),
        ),
    ]
