# Generated by Django 5.1.5 on 2025-11-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_onboardingprogress_onboardingchatdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='llm_budget_limit',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Monthly LLM budget limit in USD (soft limit with alerts)', max_digits=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='llm_budget_reset_at',
            field=models.DateTimeField(blank=True, help_text='When LLM budget counter was last reset (monthly)', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='llm_budget_spent',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Total LLM cost spent by user (resets monthly)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_intervention_type',
            field=models.CharField(blank=True, help_text='planb_switch | workload_reduction | blocker_reduction | etc.', max_length=50),
        ),
    ]
