# Generated by Django 5.1.5 on 2025-10-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed_tasks', models.JSONField(default=list)),
                ('completed_tasks_text', models.TextField(blank=True)),
                ('missed_tasks', models.JSONField(default=list)),
                ('missed_tasks_text', models.TextField(blank=True)),
                ('missed_reason', models.TextField(blank=True)),
                ('new_opportunities', models.TextField(blank=True)),
                ('ai_response', models.TextField(blank=True)),
                ('ai_recommendations', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('date_occurred', models.DateField()),
                ('ai_impact_assessment', models.CharField(choices=[('low', 'Low Impact'), ('medium', 'Medium Impact'), ('high', 'High Impact'), ('game_changer', 'Game Changer')], default='medium', max_length=20)),
                ('ai_recommendation', models.TextField(blank=True)),
                ('requires_vision_change', models.BooleanField(default=False)),
                ('user_action', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_occurred'],
            },
        ),
    ]
