# Generated by Django 5.1.5 on 2025-10-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='buffer_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='milestone',
            name='critical_tasks_done',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='milestone',
            name='critical_tasks_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='milestone',
            name='focus_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='milestone',
            name='percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='milestone',
            name='proofs',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='milestone',
            name='risk_flags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='milestone',
            name='state',
            field=models.CharField(choices=[('done', 'Done'), ('in_progress', 'In Progress'), ('next', 'Next'), ('later', 'Later'), ('at_risk', 'At Risk')], default='later', max_length=20),
        ),
    ]
