# Generated by Django 5.1.5 on 2026-01-27 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_reminders_enabled', models.BooleanField(default=True)),
                ('task_due_soon_enabled', models.BooleanField(default=True)),
                ('task_overdue_enabled', models.BooleanField(default=True)),
                ('task_completed_enabled', models.BooleanField(default=False)),
                ('community_new_post_enabled', models.BooleanField(default=True)),
                ('community_reply_enabled', models.BooleanField(default=True)),
                ('community_mention_enabled', models.BooleanField(default=True)),
                ('community_upvote_enabled', models.BooleanField(default=True)),
                ('social_new_follower_enabled', models.BooleanField(default=True)),
                ('social_like_enabled', models.BooleanField(default=True)),
                ('message_new_enabled', models.BooleanField(default=True)),
                ('message_unread_enabled', models.BooleanField(default=True)),
                ('system_update_enabled', models.BooleanField(default=True)),
                ('achievement_enabled', models.BooleanField(default=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start time e.g., 22:00', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End time e.g., 08:00', null=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('push_sound_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('task_reminder', 'Task Reminder'), ('task_due_soon', 'Task Due Soon'), ('task_overdue', 'Task Overdue'), ('task_completed', 'Task Completed'), ('community_new_post', 'New Post in Community'), ('community_reply', 'Reply to Comment'), ('community_mention', 'Mention in Post/Comment'), ('community_upvote', 'Upvote Milestone'), ('social_new_follower', 'New Follower'), ('social_like', 'Like on Post'), ('message_new', 'New Direct Message'), ('message_unread', 'Unread Messages'), ('system_update', 'System Update'), ('achievement', 'Achievement Unlocked')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx')],
            },
        ),
    ]
