# Generated by Django 5.2.10 on 2026-02-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='booking_confirmed_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='booking_requested_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='review_ready_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='session_reminder_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_reminder', 'Task Reminder'), ('task_due_soon', 'Task Due Soon'), ('task_overdue', 'Task Overdue'), ('task_completed', 'Task Completed'), ('community_new_post', 'New Post in Community'), ('community_reply', 'Reply to Comment'), ('community_mention', 'Mention in Post/Comment'), ('community_upvote', 'Upvote Milestone'), ('social_new_follower', 'New Follower'), ('social_like', 'Like on Post'), ('message_new', 'New Direct Message'), ('message_unread', 'Unread Messages'), ('system_update', 'System Update'), ('achievement', 'Achievement Unlocked'), ('booking_requested', 'New Booking Request'), ('booking_confirmed', 'Booking Confirmed'), ('session_reminder', 'Upcoming Session Reminder'), ('review_ready', 'Review Response Ready')], max_length=50),
        ),
    ]
