from django.db import models
from django.conf import settings
from django.utils import timezone


class Todo(models.Model):
    """
    Atomic Task Model
    Supports: Verb + Target + Constraint + Deliverable + Evidence + Timebox
    """
    STATUS_CHOICES = [
        ('pending', 'Pending'),  # Not scheduled yet
        ('ready', 'Ready'),  # Unblocked and ready to start
        ('in_progress', 'In Progress'),  # "Let's go" clicked
        ('done', 'Done'),
        ('skipped', 'Skipped'),
        ('blocked', 'Blocked'),  # Dependencies not met
    ]

    SOURCE_CHOICES = [
        ('ai_generated', 'AI Generated'),
        ('user_added', 'User Added'),
        ('integrated', 'AI Integrated'),  # User added, AI integrated into plan
        ('ai_agent', 'AI Agent'),  # Generated by intelligent web-searching agent
        ('daily_planner', 'Daily Planner'),  # Spawned by daily planner
        ('web_research', 'Web Research'),  # New onboarding path research tasks
    ]

    TASK_TYPE_CHOICES = [
        ('auto', 'Auto'),  # AI can fully complete
        ('copilot', 'Co-pilot'),  # Needs user input
        ('manual', 'Manual'),  # Human-only action
    ]

    DELIVERABLE_TYPE_CHOICES = [
        ('spreadsheet', 'Spreadsheet'),
        ('doc', 'Document'),
        ('email', 'Email'),
        ('recording', 'Recording'),
        ('link', 'Link'),
        ('shortlist', 'Shortlist'),
        ('file', 'File'),
        ('note', 'Note'),
        ('other', 'Other'),
    ]

    TASK_LEVEL_CHOICES = [
        ('goal', 'Goal'),  # Top-level goal (e.g., "Get into Cambridge")
        ('sub_goal', 'Sub-goal'),  # Mid-level milestone (e.g., "Prepare documents")
        ('action', 'Action'),  # Atomic actionable task (e.g., "Write SOP draft")
    ]

    ENERGY_LEVEL_CHOICES = [
        ('high', 'High Energy'),  # Morning, complex tasks, deep work
        ('medium', 'Medium'),  # Afternoon, moderate focus
        ('low', 'Low Energy'),  # Evening, light tasks, admin work
    ]

    # Core relationships
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='todos')
    vision = models.ForeignKey('vision.Vision', on_delete=models.SET_NULL, null=True, blank=True, related_name='todos')
    goalspec = models.ForeignKey('users.GoalSpec', on_delete=models.SET_NULL, null=True, blank=True, related_name='tasks', help_text="Associated goal specification from new onboarding")
    milestone = models.ForeignKey('vision.Milestone', on_delete=models.SET_NULL, null=True, blank=True, related_name='tasks')
    parent_task = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='subtasks')

    # Basic info
    title = models.CharField(max_length=500)
    description = models.TextField(blank=True)
    priority = models.IntegerField(default=2)  # 1=low, 2=medium, 3=high
    estimated_duration_minutes = models.IntegerField(null=True, blank=True)

    # Atomic task fields
    task_type = models.CharField(max_length=20, choices=TASK_TYPE_CHOICES, default='manual')
    timebox_minutes = models.IntegerField(default=30, help_text="Expected duration for this task")
    constraints = models.JSONField(default=dict, blank=True, help_text="Filters, requirements, rubrics as JSON")
    definition_of_done = models.JSONField(default=list, blank=True, help_text='[{"text": "...", "weight": 30, "completed": false}]')
    progress_percentage = models.IntegerField(default=0, help_text="Calculated from DoD + evidence")
    deliverable_type = models.CharField(max_length=20, choices=DELIVERABLE_TYPE_CHOICES, default='other')

    # NEW: Task hierarchy and smart scheduling
    task_level = models.CharField(
        max_length=20,
        choices=TASK_LEVEL_CHOICES,
        default='action',
        help_text="Hierarchy level: goal → sub_goal → action"
    )
    contribution_weight = models.FloatField(
        default=1.0,
        help_text="Weight of this task's contribution to parent goal (0.0-1.0)"
    )
    energy_level = models.CharField(
        max_length=20,
        choices=ENERGY_LEVEL_CHOICES,
        default='medium',
        help_text="Required energy level for this task"
    )
    cognitive_load = models.IntegerField(
        default=3,
        help_text="Mental effort required (1=trivial, 5=intense focus)"
    )
    estimated_energy_cost = models.IntegerField(
        default=50,
        help_text="Combined metric: timebox * cognitive_load (0-300)"
    )

    # Dependencies
    blocked_by = models.JSONField(default=list, blank=True, help_text="Array of task IDs that must complete first")
    unlocks = models.JSONField(default=list, blank=True, help_text="Array of task IDs this task will unlock")

    # "Let's Go" flow
    artifact_template = models.JSONField(default=dict, blank=True, help_text="Template for artifact creation")
    lets_go_inputs = models.JSONField(default=list, blank=True, help_text='Questions/inputs needed: [{"type": "text", "question": "..."}]')

    # Evidence & artifacts
    evidence_url = models.URLField(max_length=500, blank=True, null=True, help_text="Proof of completion")
    external_url = models.URLField(max_length=500, blank=True, null=True, help_text="LinkedIn profile, event link, course URL, etc.")
    notes = models.JSONField(default=dict, blank=True, help_text="Additional context including milestone metadata and web search results")

    # Day 1 Personalization Fields
    is_quick_win = models.BooleanField(default=False, help_text="< 30 min, high confidence task for Day 1 momentum")
    task_category = models.CharField(
        max_length=20,
        choices=[
            ('quick_win', 'Quick Win'),
            ('learning', 'Learning'),
            ('foundation', 'Foundation'),
            ('regular', 'Regular'),
        ],
        default='regular',
        help_text="Task category for Day 1 personalization and UI display"
    )

    # Idempotency
    idempotency_key = models.CharField(max_length=100, blank=True, unique=True, null=True, help_text="Prevent duplicate creation")

    # Scheduling
    scheduled_date = models.DateField()
    scheduled_time = models.TimeField(null=True, blank=True)
    source = models.CharField(max_length=20, choices=SOURCE_CHOICES, default='ai_generated')

    # Status tracking
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='ready')
    completed_at = models.DateTimeField(null=True, blank=True)
    skipped_at = models.DateTimeField(null=True, blank=True)
    skip_reason = models.TextField(blank=True)

    # Notifications
    reminder_sent = models.BooleanField(default=False)
    reminder_time = models.DateTimeField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['scheduled_date', 'priority', 'created_at']
        indexes = [
            models.Index(fields=['user', 'scheduled_date', 'status']),
        ]

    def __str__(self):
        return f"{self.user.email} - {self.title} ({self.scheduled_date})"

    @property
    def is_overdue(self):
        """Check if task is overdue"""
        if self.status in ['done', 'skipped']:
            return False
        return self.scheduled_date < timezone.now().date()

    @property
    def days_overdue(self):
        """Calculate days overdue"""
        if not self.is_overdue:
            return 0
        return (timezone.now().date() - self.scheduled_date).days

    def calculate_progress(self):
        """
        Calculate progress from Definition of Done + evidence
        Progress = weighted sum of completed DoD items + evidence bonus
        """
        if not self.definition_of_done:
            # Fallback: if no DoD, use simple status-based progress
            if self.status == 'done':
                return 100
            elif self.status == 'in_progress':
                return 50
            return 0

        total_weight = sum(item.get('weight', 0) for item in self.definition_of_done)
        if total_weight == 0:
            return 0

        completed_weight = sum(
            item.get('weight', 0)
            for item in self.definition_of_done
            if item.get('completed', False)
        )

        progress = int((completed_weight / total_weight) * 100)

        # Evidence bonus: +10% if evidence attached
        if self.evidence_url:
            progress = min(100, progress + 10)

        return progress

    def update_progress(self):
        """Update progress_percentage field"""
        self.progress_percentage = self.calculate_progress()
        self.save(update_fields=['progress_percentage'])

    def is_blocked(self):
        """Check if task is blocked by dependencies"""
        if not self.blocked_by:
            return False

        # Check if any blocker tasks are not done
        blocker_tasks = Todo.objects.filter(
            id__in=self.blocked_by,
            user=self.user
        ).exclude(status='done')

        return blocker_tasks.exists()

    def unlock_dependents(self):
        """When this task completes, unlock dependent tasks"""
        if not self.unlocks:
            return

        dependent_tasks = Todo.objects.filter(
            id__in=self.unlocks,
            user=self.user
        )

        for task in dependent_tasks:
            if not task.is_blocked():
                task.status = 'ready'
                task.save(update_fields=['status'])


# Import artifact models to make them discoverable by Django
from .artifact_models import TaskArtifact, TaskEvidence, TaskRun, AutomationConsent, AutomationAudit

# Import advanced task models
from .advanced_models import RecurringTaskTemplate, TaskCompletion, AIInsight, TaskConversation
