# Generated by Django 5.1.5 on 2025-10-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('priority', models.IntegerField(default=2)),
                ('estimated_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('ai_generated', 'AI Generated'), ('user_added', 'User Added'), ('integrated', 'AI Integrated')], default='ai_generated', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('skipped', 'Skipped'), ('rescheduled', 'Rescheduled')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('skipped_at', models.DateTimeField(blank=True, null=True)),
                ('skip_reason', models.TextField(blank=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scheduled_date', 'priority', 'created_at'],
            },
        ),
    ]
