# Generated by Django 5.1.5 on 2025-10-04 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_initial'),
        ('vision', '0002_milestone_buffer_days_milestone_critical_tasks_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='vision.milestone'),
        ),
    ]
