# Generated by Django 5.1.5 on 2025-10-15 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_todo_external_url_todo_notes_alter_todo_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='artifact_template',
            field=models.JSONField(blank=True, default=dict, help_text='Template for artifact creation'),
        ),
        migrations.AddField(
            model_name='todo',
            name='blocked_by',
            field=models.JSONField(blank=True, default=list, help_text='Array of task IDs that must complete first'),
        ),
        migrations.AddField(
            model_name='todo',
            name='constraints',
            field=models.JSONField(blank=True, default=dict, help_text='Filters, requirements, rubrics as JSON'),
        ),
        migrations.AddField(
            model_name='todo',
            name='definition_of_done',
            field=models.JSONField(blank=True, default=list, help_text='[{"text": "...", "weight": 30, "completed": false}]'),
        ),
        migrations.AddField(
            model_name='todo',
            name='deliverable_type',
            field=models.CharField(choices=[('spreadsheet', 'Spreadsheet'), ('doc', 'Document'), ('email', 'Email'), ('recording', 'Recording'), ('link', 'Link'), ('shortlist', 'Shortlist'), ('file', 'File'), ('note', 'Note'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='todo',
            name='evidence_url',
            field=models.URLField(blank=True, help_text='Proof of completion', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Prevent duplicate creation', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='lets_go_inputs',
            field=models.JSONField(blank=True, default=list, help_text='Questions/inputs needed: [{"type": "text", "question": "..."}]'),
        ),
        migrations.AddField(
            model_name='todo',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='todos.todo'),
        ),
        migrations.AddField(
            model_name='todo',
            name='progress_percentage',
            field=models.IntegerField(default=0, help_text='Calculated from DoD + evidence'),
        ),
        migrations.AddField(
            model_name='todo',
            name='task_type',
            field=models.CharField(choices=[('auto', 'Auto'), ('copilot', 'Co-pilot'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='todo',
            name='timebox_minutes',
            field=models.IntegerField(default=30, help_text='Expected duration for this task'),
        ),
        migrations.AddField(
            model_name='todo',
            name='unlocks',
            field=models.JSONField(blank=True, default=list, help_text='Array of task IDs this task will unlock'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='source',
            field=models.CharField(choices=[('ai_generated', 'AI Generated'), ('user_added', 'User Added'), ('integrated', 'AI Integrated'), ('ai_agent', 'AI Agent'), ('daily_planner', 'Daily Planner')], default='ai_generated', max_length=20),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('in_progress', 'In Progress'), ('done', 'Done'), ('skipped', 'Skipped'), ('blocked', 'Blocked')], default='pending', max_length=20),
        ),
    ]
