# Generated by Django 5.1.5 on 2025-10-15 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_todo_artifact_template_todo_blocked_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create_docs', models.BooleanField(default=False, help_text='Allow AI to create Google Docs')),
                ('can_create_sheets', models.BooleanField(default=False, help_text='Allow AI to create Spreadsheets')),
                ('can_create_calendar', models.BooleanField(default=False, help_text='Allow AI to create calendar events')),
                ('can_draft_emails', models.BooleanField(default=False, help_text='Allow AI to draft emails')),
                ('can_send_emails', models.BooleanField(default=False, help_text='Allow AI to send emails (requires preview)')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revoked', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='automation_consent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('shortlist', 'Shortlist'), ('spreadsheet', 'Spreadsheet'), ('doc', 'Document'), ('email', 'Email Draft'), ('recording', 'Recording'), ('link', 'Link'), ('file', 'File'), ('json', 'JSON Data')], max_length=20)),
                ('content', models.JSONField(blank=True, default=dict, help_text='Structured content (for shortlist, spreadsheet, etc.)')),
                ('text_content', models.TextField(blank=True, help_text='Text content (for docs, emails, etc.)')),
                ('url', models.URLField(blank=True, help_text='Link to Google Doc/Sheet, etc.', max_length=500)),
                ('file', models.FileField(blank=True, null=True, upload_to='artifacts/')),
                ('created_by', models.CharField(choices=[('ai', 'AI'), ('user', 'User'), ('ai_user', 'AI + User')], default='ai', max_length=20)),
                ('sources', models.JSONField(blank=True, default=list, help_text='[{"title": "...", "url": "...", "captured_at": "..."}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='todos.todo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('created_doc', 'Created Document'), ('created_sheet', 'Created Spreadsheet'), ('created_event', 'Created Calendar Event'), ('drafted_email', 'Drafted Email'), ('sent_email', 'Sent Email'), ('generated_artifact', 'Generated Artifact')], max_length=30)),
                ('actor', models.CharField(choices=[('ai', 'AI'), ('user', 'User')], default='ai', help_text='Who performed this action', max_length=20)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_audits', to='todos.todo')),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todos.taskartifact')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TaskEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('file', 'File Upload'), ('link', 'Link/URL'), ('screenshot', 'Screenshot'), ('note', 'Text Note'), ('photo', 'Photo')], max_length=20)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('file', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('note', models.TextField(blank=True, help_text='Text description or note')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='todos.todo')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Task evidence',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_inputs', models.JSONField(default=list, help_text='[{"timestamp": "...", "input_type": "text|chip", "value": "..."}]')),
                ('ai_responses', models.JSONField(default=list, help_text='[{"timestamp": "...", "message": "...", "suggested_actions": [...]}]')),
                ('duration_seconds', models.IntegerField(default=0)),
                ('interactions_count', models.IntegerField(default=0, help_text='Number of back-and-forth exchanges')),
                ('completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('final_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run', to='todos.taskartifact')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='todos.todo')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='taskartifact',
            index=models.Index(fields=['task', 'artifact_type'], name='todos_taska_task_id_5c2a09_idx'),
        ),
        migrations.AddIndex(
            model_name='automationaudit',
            index=models.Index(fields=['task', 'timestamp'], name='todos_autom_task_id_d188f3_idx'),
        ),
    ]
