# Generated by Django 5.1.5 on 2025-11-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_taskconversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_quick_win',
            field=models.BooleanField(default=False, help_text='< 30 min, high confidence task for Day 1 momentum'),
        ),
        migrations.AddField(
            model_name='todo',
            name='task_category',
            field=models.CharField(choices=[('quick_win', 'Quick Win'), ('learning', 'Learning'), ('foundation', 'Foundation'), ('regular', 'Regular')], default='regular', help_text='Task category for Day 1 personalization and UI display', max_length=20),
        ),
    ]
