# Generated by Django 5.1.5 on 2026-01-26 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0013_alter_todo_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(help_text='Emoji icon for this category', max_length=10)),
                ('color', models.CharField(help_text='Hex color code (e.g., #3B82F6)', max_length=7)),
                ('description', models.TextField(blank=True, help_text='Detailed description of this category')),
                ('is_application_specific', models.BooleanField(default=True, help_text='True for college application categories, False for generic productivity')),
                ('order', models.IntegerField(default=0, help_text='Display order in UI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Task Categories',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Application-specific category (Documents, Essays, Portfolio, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='todos.taskcategory'),
        ),
    ]
