# Generated by Django 5.1.5 on 2026-01-26 13:28

from django.db import migrations


def seed_task_categories(apps, schema_editor):
    """
    Seed 7 application-specific task categories for college application platform.
    These replace generic categories (study, career, sport) with domain-specific ones.
    """
    TaskCategory = apps.get_model('todos', 'TaskCategory')

    categories = [
        {
            'name': 'Documents',
            'icon': '📄',
            'color': '#3B82F6',
            'description': 'Application documents, transcripts, certificates, and official paperwork',
            'is_application_specific': True,
            'order': 1,
        },
        {
            'name': 'Essays',
            'icon': '📝',
            'color': '#10B981',
            'description': 'Personal statements, supplemental essays, writing samples, and essay reviews',
            'is_application_specific': True,
            'order': 2,
        },
        {
            'name': 'Portfolio',
            'icon': '💼',
            'color': '#8B5CF6',
            'description': 'Creative portfolios, project showcases, work samples, and achievement documentation',
            'is_application_specific': True,
            'order': 3,
        },
        {
            'name': 'SAT Prep',
            'icon': '📊',
            'color': '#F59E0B',
            'description': 'SAT preparation, practice tests, study sessions, and test registration',
            'is_application_specific': True,
            'order': 4,
        },
        {
            'name': 'IELTS Prep',
            'icon': '🗣',
            'color': '#F97316',
            'description': 'IELTS preparation, speaking practice, writing practice, and test registration',
            'is_application_specific': True,
            'order': 5,
        },
        {
            'name': 'Applications',
            'icon': '🎓',
            'color': '#EF4444',
            'description': 'College applications, Common App, university-specific apps, and submission tracking',
            'is_application_specific': True,
            'order': 6,
        },
        {
            'name': 'Extracurriculars',
            'icon': '🎯',
            'color': '#6B7280',
            'description': 'Activities, leadership, community service, competitions, and achievement documentation',
            'is_application_specific': True,
            'order': 7,
        },
    ]

    for category_data in categories:
        TaskCategory.objects.get_or_create(
            name=category_data['name'],
            defaults=category_data
        )


def reverse_seed(apps, schema_editor):
    """
    Reverse function to remove seeded categories if migration is rolled back.
    """
    TaskCategory = apps.get_model('todos', 'TaskCategory')
    TaskCategory.objects.filter(name__in=[
        'Documents',
        'Essays',
        'Portfolio',
        'SAT Prep',
        'IELTS Prep',
        'Applications',
        'Extracurriculars',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0014_taskcategory_todo_category'),
    ]

    operations = [
        migrations.RunPython(seed_task_categories, reverse_seed),
    ]
