# Generated by Django 5.1.5 on 2026-01-26 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0015_seed_task_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcompletion',
            name='completion_status',
            field=models.CharField(choices=[('fully_completed', 'Fully Completed'), ('partially_completed', 'Partially Completed'), ('not_completed', 'Not Completed')], default='fully_completed', help_text='How completely the task was finished', max_length=30),
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='files_attached',
            field=models.JSONField(blank=True, default=list, help_text="List of attached files as evidence: [{'url': '...', 'type': 'pdf', 'name': 'essay.pdf'}]"),
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='quality_rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Very Easy'), (2, 'Easy'), (3, 'Medium'), (4, 'Hard'), (5, 'Very Hard')], help_text='Quality of work produced (1=Poor, 5=Excellent)', null=True),
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='result_data',
            field=models.JSONField(blank=True, default=dict, help_text='\n        Category-specific results:\n        - essay_word_count: {"word_count": 650, "prompt_type": "personal_statement"}\n        - test_score: {"score": 1450, "math": 720, "reading_writing": 730, "test_date": "2025-03-15"}\n        - portfolio_upload: {"file_count": 5, "project_urls": ["..."]}\n        - practice_test: {"score": 1400, "section_scores": {...}, "focus_areas": ["algebra", "grammar"]}\n        '),
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='result_type',
            field=models.CharField(choices=[('general', 'General Task'), ('essay_word_count', 'Essay Word Count'), ('test_score', 'Test Score'), ('portfolio_upload', 'Portfolio Upload'), ('document_submission', 'Document Submission'), ('application_submit', 'Application Submitted'), ('practice_test', 'Practice Test'), ('meeting_complete', 'Meeting/Call Complete'), ('research_complete', 'Research Complete')], default='general', help_text='Type of result for this task', max_length=30),
        ),
        migrations.AddIndex(
            model_name='taskcompletion',
            index=models.Index(fields=['result_type'], name='todos_taskc_result__a10e5e_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcompletion',
            index=models.Index(fields=['completion_status'], name='todos_taskc_complet_5582fc_idx'),
        ),
    ]
