# Generated by Django 5.2.10 on 2026-02-16 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0016_taskcompletion_completion_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('essay_type', models.CharField(choices=[('personal_statement', 'Personal Statement'), ('supplemental', 'Supplemental Essay'), ('why_college', 'Why This College'), ('why_major', 'Why This Major'), ('community', 'Community Service'), ('leadership', 'Leadership Experience'), ('challenge', 'Overcoming Challenge'), ('achievement', 'Significant Achievement'), ('activity', 'Extracurricular Activity'), ('creative', 'Creative/Unconventional')], max_length=50)),
                ('prompt', models.TextField(help_text='Essay prompt/question')),
                ('word_count_min', models.IntegerField(default=250)),
                ('word_count_max', models.IntegerField(default=650)),
                ('universities', models.JSONField(default=list, help_text='List of university names that use this essay type')),
                ('structure_outline', models.JSONField(help_text='Suggested paragraph structure with sections and word counts')),
                ('key_themes', models.JSONField(default=list, help_text='Suggested themes to cover in this essay')),
                ('tips', models.TextField(blank=True, help_text='Writing tips and best practices for this essay type')),
                ('sample_essays', models.JSONField(default=list, help_text='Example essays for reference (anonymized)')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Essay Template',
                'verbose_name_plural': 'Essay Templates',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EssayProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('essay_type', models.CharField(max_length=50)),
                ('target_university', models.CharField(blank=True, max_length=200)),
                ('target_prompt', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('brainstorming', 'Brainstorming'), ('outlining', 'Outlining'), ('drafting', 'Drafting'), ('reviewing', 'Reviewing'), ('polishing', 'Polishing'), ('completed', 'Completed')], default='brainstorming', max_length=20)),
                ('current_draft', models.TextField(blank=True)),
                ('word_count', models.IntegerField(default=0)),
                ('revision_count', models.IntegerField(default=0)),
                ('brainstorming_notes', models.JSONField(default=list, help_text='AI-generated topic ideas and brainstorming results')),
                ('selected_topic', models.JSONField(blank=True, help_text="User's chosen topic from brainstorming", null=True)),
                ('outline_suggestions', models.JSONField(blank=True, help_text='AI-generated outline for selected topic', null=True)),
                ('feedback_history', models.JSONField(default=list, help_text='History of AI feedback on drafts')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('word_count_goal', models.IntegerField(default=650)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='essay_project', to='todos.todo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_projects', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='todos.essaytemplate')),
            ],
            options={
                'verbose_name': 'Essay Project',
                'verbose_name_plural': 'Essay Projects',
                'ordering': ['deadline', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='EssayFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_content', models.TextField()),
                ('draft_word_count', models.IntegerField()),
                ('ai_strengths', models.JSONField(default=list, help_text='List of strengths identified by AI')),
                ('ai_improvements', models.JSONField(default=list, help_text='List of suggested improvements from AI')),
                ('ai_structure_feedback', models.TextField(blank=True)),
                ('ai_content_feedback', models.TextField(blank=True)),
                ('ai_voice_feedback', models.TextField(blank=True)),
                ('ai_grammar_feedback', models.TextField(blank=True)),
                ('ai_score', models.IntegerField(blank=True, help_text='AI quality score (1-10)', null=True)),
                ('ai_detailed_feedback', models.TextField(blank=True)),
                ('human_feedback', models.TextField(blank=True)),
                ('human_score', models.IntegerField(blank=True, null=True)),
                ('feedback_type', models.CharField(default='ai', help_text='Type of feedback: ai, human, or both', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('human_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('essay_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_sessions', to='todos.essayproject')),
            ],
            options={
                'verbose_name': 'Essay Feedback',
                'verbose_name_plural': 'Essay Feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='essayproject',
            index=models.Index(fields=['user', 'status'], name='todos_essay_user_id_f870cb_idx'),
        ),
        migrations.AddIndex(
            model_name='essayproject',
            index=models.Index(fields=['user', 'essay_type'], name='todos_essay_user_id_ab1cef_idx'),
        ),
    ]
