# Generated by Django 5.2.10 on 2026-02-25 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0017_add_essay_models"),
        (
            "university_database",
            "0004_countryrequirement_default_essay_required_and_more",
        ),
        ("users", "0019_userprofile_activity_visibility_userprofile_bio_and_more"),
        ("vision", "0002_milestone_buffer_days_milestone_critical_tasks_done_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="alternative_path",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Suggested alternative (e.g., foundation program)",
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="dedupe_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique key to prevent duplicate tasks. REQUIRED for auto-generated tasks.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="due_date",
            field=models.DateField(
                blank=True,
                help_text="Internal target date for completing this task",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="is_auto_generated",
            field=models.BooleanField(
                default=False,
                help_text="True = generated by system, False = user-created",
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="is_blocker",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="If true, this task blocks admission",
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Example: 'University requires IELTS 7.5, you have 7.0'",
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="requirement_type",
            field=models.CharField(
                choices=[
                    ("eligibility_gap", "Eligibility Gap"),
                    ("application", "Application Step"),
                    ("document", "Document Preparation"),
                    ("test", "Test Preparation"),
                    ("foundation", "Foundation Preparation"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="other",
                help_text="Type of requirement for this task",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="university",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated university for this task",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="todos",
                to="university_database.university",
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="university_deadline",
            field=models.DateField(
                blank=True,
                help_text="Relevant deadline for this university's task",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="source",
            field=models.CharField(
                choices=[
                    ("ai_generated", "AI Generated"),
                    ("user_added", "User Added"),
                    ("integrated", "AI Integrated"),
                    ("ai_agent", "AI Agent"),
                    ("daily_planner", "Daily Planner"),
                    ("web_research", "Web Research"),
                    ("country_rule", "Country Rule"),
                    ("university_rule", "University Rule"),
                    ("program_rule", "Program Rule"),
                    ("user_missing_data", "User Missing Data"),
                    ("application_portal", "Application Portal"),
                    ("country_default", "Country Default (assumed)"),
                ],
                default="ai_generated",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="todo",
            index=models.Index(
                fields=["user", "university"], name="todos_todo_user_id_07007b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="todo",
            index=models.Index(
                fields=["user", "is_blocker"], name="todos_todo_user_id_89fb76_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="todo",
            index=models.Index(
                fields=["user", "is_auto_generated"],
                name="todos_todo_user_id_735e90_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="todo",
            index=models.Index(
                fields=["user", "dedupe_key"], name="todos_todo_user_id_8f46fc_idx"
            ),
        ),
    ]
