# Generated by Django 5.2.10 on 2026-02-25 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0018_todo_alternative_path_todo_dedupe_key_todo_due_date_and_more'),
        ('university_database', '0004_countryrequirement_default_essay_required_and_more'),
        ('users', '0019_userprofile_activity_visibility_userprofile_bio_and_more'),
        ('vision', '0002_milestone_buffer_days_milestone_critical_tasks_done_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='todo',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key__isnull', False), models.Q(('dedupe_key', ''), _negated=True)), fields=('user', 'dedupe_key'), name='unique_user_dedupe_key', violation_error_message='A task with this dedupe_key already exists for this user.'),
        ),
    ]
