# Generated by Django 5.2.10 on 2026-02-26 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0019_add_dedupe_key_constraint'),
        ('university_database', '0004_countryrequirement_default_essay_required_and_more'),
        ('users', '0019_userprofile_activity_visibility_userprofile_bio_and_more'),
        ('vision', '0002_milestone_buffer_days_milestone_critical_tasks_done_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='country',
            field=models.CharField(blank=True, db_index=True, help_text='Country for country-specific tasks', max_length=100),
        ),
        migrations.AddField(
            model_name='todo',
            name='depends_on',
            field=models.JSONField(blank=True, default=list, help_text='List of dedupe_keys this task depends on'),
        ),
        migrations.AddField(
            model_name='todo',
            name='evidence_fields',
            field=models.JSONField(blank=True, default=list, help_text='List of evidence fields required (uniform naming)'),
        ),
        migrations.AddField(
            model_name='todo',
            name='evidence_status',
            field=models.CharField(choices=[('missing', 'No evidence uploaded'), ('partial', 'Some evidence uploaded'), ('complete', 'All evidence uploaded')], db_index=True, default='missing', help_text='Status of evidence upload', max_length=20),
        ),
        migrations.AddField(
            model_name='todo',
            name='link_type',
            field=models.CharField(blank=True, choices=[('portal', 'Application Portal'), ('visa', 'Visa Requirements'), ('scholarship', 'Scholarship Info'), ('requirement_page', 'Official Requirement Page'), ('upload', 'Document Upload'), ('info', 'Information Page')], help_text='Type of link', max_length=20),
        ),
        migrations.AddField(
            model_name='todo',
            name='link_url',
            field=models.URLField(blank=True, help_text='URL to application portal or requirement page', max_length=500),
        ),
        migrations.AddField(
            model_name='todo',
            name='requirement_key',
            field=models.CharField(blank=True, db_index=True, help_text="Requirement key from RequirementInstance (e.g., 'passport_validity', 'ielts_score')", max_length=100),
        ),
        migrations.AddField(
            model_name='todo',
            name='scope',
            field=models.CharField(blank=True, choices=[('global', 'Global'), ('country', 'Country'), ('university', 'University'), ('scholarship', 'Scholarship')], db_index=True, help_text='Scope of this task', max_length=20),
        ),
        migrations.AddField(
            model_name='todo',
            name='stage',
            field=models.CharField(blank=True, choices=[('strategy', 'Strategy'), ('shortlist', 'Shortlist'), ('docs', 'Documents'), ('essays', 'Essays'), ('apply', 'Apply'), ('visa', 'Visa'), ('arrival', 'Post-Admission')], db_index=True, help_text='Stage of the application process', max_length=20),
        ),
        migrations.AddField(
            model_name='todo',
            name='university_checklist',
            field=models.JSONField(blank=True, default=dict, help_text='Per-university checklist for global tasks {uni_id: {required, status, ...}}'),
        ),
        migrations.AddField(
            model_name='todo',
            name='validation_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Validation'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('not_applicable', 'Not Applicable')], help_text='Validation status for documents/essays', max_length=20),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['user', 'scope'], name='todos_todo_user_id_129130_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['user', 'stage'], name='todos_todo_user_id_58bfc2_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['user', 'requirement_key'], name='todos_todo_user_id_bab55a_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['user', 'country'], name='todos_todo_user_id_01b5ec_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['user', 'evidence_status'], name='todos_todo_user_id_5e2afc_idx'),
        ),
    ]
