# Generated by Django 5.1.5 on 2025-10-19 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatconversation_chatmessage_conversation_and_more'),
        ('todos', '0010_taskconversation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='task',
            field=models.ForeignKey(blank=True, help_text='If set, this is a task-specific conversation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to='todos.todo'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['task'], name='chat_chatco_task_id_250189_idx'),
        ),
    ]
