# Generated by Django 5.1.5 on 2025-10-19 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBehaviorPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(choices=[('failure_time', 'Failure Time Pattern'), ('failure_category', 'Failure Category Pattern'), ('procrastination', 'Procrastination Pattern'), ('chat_topics', 'Chat Topics Pattern')], help_text='Type of behavior pattern detected', max_length=30)),
                ('time_window_start', models.DateField(help_text='Start date of analyzed period')),
                ('time_window_end', models.DateField(help_text='End date of analyzed period')),
                ('data', models.JSONField(default=dict, help_text='\n        Pattern-specific data:\n        failure_time: {"time_slot": "evening", "failure_rate": 0.7, "tasks_affected": 5}\n        failure_category: {"category": "career", "failure_rate": 0.6, "total_tasks": 10}\n        procrastination: {"category": "study", "avg_delay_days": 3.5, "tasks_count": 8}\n        chat_topics: {"topic": "interview prep", "frequency": 12, "sentiment": "anxious"}\n        ')),
                ('confidence_score', models.FloatField(default=0.5, help_text='AI confidence in this pattern (0.0-1.0)')),
                ('first_detected', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this pattern is still relevant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_patterns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confidence_score', '-last_updated'],
                'indexes': [models.Index(fields=['user', 'pattern_type', 'is_active'], name='analytics_u_user_id_c6a4be_idx'), models.Index(fields=['time_window_start', 'time_window_end'], name='analytics_u_time_wi_a91f67_idx')],
                'unique_together': {('user', 'pattern_type', 'time_window_start')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(help_text='Monday of the week')),
                ('week_end_date', models.DateField(help_text='Sunday of the week')),
                ('insights', models.JSONField(default=list, help_text='\n        Array of insights: [\n            {\n                "type": "failure_pattern",\n                "icon": "🔴",\n                "message": "You skipped career tasks 3 times - all scheduled in evening",\n                "evidence": {"tasks": [1, 2, 3], "category": "career", "time": "evening"},\n                "priority": 3\n            },\n            {\n                "type": "chat_topic",\n                "icon": "💬",\n                "message": "Most discussed: interview prep (5 times)",\n                "evidence": {"topic": "interview prep", "count": 5},\n                "priority": 2\n            }\n        ]\n        ')),
                ('action_items', models.JSONField(default=list, help_text='\n        Array of actionable suggestions: [\n            {\n                "action": "reschedule_tasks",\n                "description": "Move career tasks to morning (9-11am)",\n                "task_ids": [1, 2, 3],\n                "impact": "high"\n            },\n            {\n                "action": "create_recurring",\n                "description": "Add recurring \'Interview prep\' task every Tuesday",\n                "impact": "medium"\n            }\n        ]\n        ')),
                ('full_message', models.TextField(help_text='Complete reflection message generated by AI')),
                ('is_read', models.BooleanField(default=False)),
                ('notified_at', models.DateTimeField(blank=True, help_text='When push notification was sent', null=True)),
                ('shown_in_chat', models.BooleanField(default=False, help_text='Whether reflection was shown in chat')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('patterns_analyzed', models.IntegerField(default=0, help_text='Number of behavior patterns analyzed')),
                ('generation_method', models.CharField(choices=[('scheduled', 'Scheduled (Sunday)'), ('on_demand', 'On Demand (User Request)')], default='scheduled', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reflections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start_date'],
                'indexes': [models.Index(fields=['user', '-week_start_date'], name='analytics_w_user_id_70f56b_idx'), models.Index(fields=['is_read'], name='analytics_w_is_read_d5861f_idx')],
                'unique_together': {('user', 'week_start_date')},
            },
        ),
    ]
