# Generated by Django 5.1.5 on 2025-10-19 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of this brief')),
                ('greeting_message', models.TextField(help_text='Personalized greeting based on time of day')),
                ('top_priorities', models.JSONField(default=list, help_text='\n        Top priority tasks for today: [\n            {\n                "task_id": 1,\n                "title": "Speaking practice",\n                "reason": "high priority + deadline tomorrow",\n                "deadline": "2025-10-20",\n                "timebox_minutes": 60\n            }\n        ]\n        ')),
                ('workload_percentage', models.IntegerField(default=0, help_text='Percentage of day filled with tasks (0-100+)')),
                ('workload_status', models.CharField(choices=[('light', 'Light'), ('optimal', 'Optimal'), ('heavy', 'Heavy'), ('overloaded', 'Overloaded')], default='optimal', max_length=20)),
                ('total_timebox_minutes', models.IntegerField(default=0, help_text='Total minutes of scheduled tasks')),
                ('available_minutes', models.IntegerField(default=480, help_text="User's available minutes for the day")),
                ('warnings', models.JSONField(default=list, help_text='\n        Warnings and reminders: [\n            {\n                "type": "low_progress",\n                "category": "study",\n                "message": "Учёба 0% прогресса за неделю",\n                "severity": "medium"\n            },\n            {\n                "type": "deadline",\n                "message": "Интервью с Microsoft завтра в 14:00",\n                "severity": "high"\n            }\n        ]\n        ')),
                ('smart_suggestions', models.JSONField(default=list, help_text='\n        Smart suggestions: [\n            {\n                "type": "category_balance",\n                "message": "Добавить задачу \'Research CEU requirements\'?",\n                "action": {\n                    "type": "add_task",\n                    "title": "Research CEU requirements",\n                    "category": "study",\n                    "timebox": 30\n                }\n            },\n            {\n                "type": "quick_win",\n                "message": "У тебя есть 2 quick win задачи (15 мин)",\n                "task_ids": [5, 6]\n            }\n        ]\n        ')),
                ('weekly_progress', models.JSONField(default=dict, help_text='\n        Weekly progress summary: {\n            "completion_rate": 72,\n            "completed_tasks": 18,\n            "total_tasks": 25,\n            "overdue_tasks": 2,\n            "streak_days": 5\n        }\n        ')),
                ('full_message', models.TextField(help_text='Complete formatted brief message for display')),
                ('shown_in_push', models.BooleanField(default=False)),
                ('shown_in_app', models.BooleanField(default=False)),
                ('shown_in_chat', models.BooleanField(default=False)),
                ('first_shown_at', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('regenerated_at', models.DateTimeField(blank=True, help_text='Last time brief was regenerated', null=True)),
                ('generation_trigger', models.CharField(choices=[('scheduled', 'Scheduled (7 AM)'), ('on_login', 'On Login'), ('manual', 'Manual Request')], default='scheduled', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_briefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='analytics_d_user_id_42fd84_idx'), models.Index(fields=['date'], name='analytics_d_date_5ae327_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
