from django.conf import settings
from django.db import models
from django.db.models import Q
from django.utils import timezone


class TaskCategory(models.Model):
    """
    Application-specific task categories for college application platform.
    Replaces generic categories (study, career, sport) with domain-specific ones.
    """

    name = models.CharField(max_length=100, unique=True)
    icon = models.CharField(max_length=10, help_text="Emoji icon for this category")
    color = models.CharField(max_length=7, help_text="Hex color code (e.g., #3B82F6)")
    description = models.TextField(
        blank=True, help_text="Detailed description of this category"
    )
    is_application_specific = models.BooleanField(
        default=True,
        help_text="True for college application categories, False for generic productivity",
    )
    order = models.IntegerField(default=0, help_text="Display order in UI")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["order"]
        verbose_name_plural = "Task Categories"

    def __str__(self):
        return f"{self.icon} {self.name}"


class Todo(models.Model):
    """
    Atomic Task Model
    Supports: Verb + Target + Constraint + Deliverable + Evidence + Timebox
    """

    STATUS_CHOICES = [
        ("pending", "Pending"),  # Not scheduled yet
        ("ready", "Ready"),  # Unblocked and ready to start
        ("in_progress", "In Progress"),  # "Let's go" clicked
        ("done", "Done"),
        ("skipped", "Skipped"),
        ("blocked", "Blocked"),  # Dependencies not met
    ]

    SOURCE_CHOICES = [
        ("ai_generated", "AI Generated"),
        ("user_added", "User Added"),
        ("integrated", "AI Integrated"),  # User added, AI integrated into plan
        ("ai_agent", "AI Agent"),  # Generated by intelligent web-searching agent
        ("daily_planner", "Daily Planner"),  # Spawned by daily planner
        ("web_research", "Web Research"),  # New onboarding path research tasks
        # NEW: Eligibility-first task sources
        ("country_rule", "Country Rule"),
        ("university_rule", "University Rule"),
        ("program_rule", "Program Rule"),
        ("user_missing_data", "User Missing Data"),
        ("application_portal", "Application Portal"),
        ("country_default", "Country Default (assumed)"),
    ]

    TASK_TYPE_CHOICES = [
        ("auto", "Auto"),  # AI can fully complete
        ("copilot", "Co-pilot"),  # Needs user input
        ("manual", "Manual"),  # Human-only action
    ]

    DELIVERABLE_TYPE_CHOICES = [
        ("spreadsheet", "Spreadsheet"),
        ("doc", "Document"),
        ("email", "Email"),
        ("recording", "Recording"),
        ("link", "Link"),
        ("shortlist", "Shortlist"),
        ("file", "File"),
        ("note", "Note"),
        ("other", "Other"),
    ]

    TASK_LEVEL_CHOICES = [
        ("goal", "Goal"),  # Top-level goal (e.g., "Get into Cambridge")
        ("sub_goal", "Sub-goal"),  # Mid-level milestone (e.g., "Prepare documents")
        ("action", "Action"),  # Atomic actionable task (e.g., "Write SOP draft")
    ]

    ENERGY_LEVEL_CHOICES = [
        ("high", "High Energy"),  # Morning, complex tasks, deep work
        ("medium", "Medium"),  # Afternoon, moderate focus
        ("low", "Low Energy"),  # Evening, light tasks, admin work
    ]

    # Core relationships
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="todos"
    )
    vision = models.ForeignKey(
        "vision.Vision",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="todos",
    )
    goalspec = models.ForeignKey(
        "users.GoalSpec",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="tasks",
        help_text="Associated goal specification from new onboarding",
    )
    milestone = models.ForeignKey(
        "vision.Milestone",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="tasks",
    )
    parent_task = models.ForeignKey(
        "self", on_delete=models.CASCADE, null=True, blank=True, related_name="subtasks"
    )
    category = models.ForeignKey(
        TaskCategory,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="tasks",
        help_text="Application-specific category (Documents, Essays, Portfolio, etc.)",
    )

    # Basic info
    title = models.CharField(max_length=500)
    description = models.TextField(blank=True)
    priority = models.IntegerField(default=2)  # 1=low, 2=medium, 3=high
    estimated_duration_minutes = models.IntegerField(null=True, blank=True)

    # Atomic task fields
    task_type = models.CharField(
        max_length=20, choices=TASK_TYPE_CHOICES, default="manual"
    )
    timebox_minutes = models.IntegerField(
        default=30, help_text="Expected duration for this task"
    )
    constraints = models.JSONField(
        default=dict, blank=True, help_text="Filters, requirements, rubrics as JSON"
    )
    definition_of_done = models.JSONField(
        default=list,
        blank=True,
        help_text='[{"text": "...", "weight": 30, "completed": false}]',
    )
    progress_percentage = models.IntegerField(
        default=0, help_text="Calculated from DoD + evidence"
    )
    deliverable_type = models.CharField(
        max_length=20, choices=DELIVERABLE_TYPE_CHOICES, default="other"
    )

    # NEW: Task hierarchy and smart scheduling
    task_level = models.CharField(
        max_length=20,
        choices=TASK_LEVEL_CHOICES,
        default="action",
        help_text="Hierarchy level: goal → sub_goal → action",
    )
    contribution_weight = models.FloatField(
        default=1.0,
        help_text="Weight of this task's contribution to parent goal (0.0-1.0)",
    )
    energy_level = models.CharField(
        max_length=20,
        choices=ENERGY_LEVEL_CHOICES,
        default="medium",
        help_text="Required energy level for this task",
    )
    cognitive_load = models.IntegerField(
        default=3, help_text="Mental effort required (1=trivial, 5=intense focus)"
    )
    estimated_energy_cost = models.IntegerField(
        default=50, help_text="Combined metric: timebox * cognitive_load (0-300)"
    )

    # Dependencies
    blocked_by = models.JSONField(
        default=list, blank=True, help_text="Array of task IDs that must complete first"
    )
    unlocks = models.JSONField(
        default=list, blank=True, help_text="Array of task IDs this task will unlock"
    )

    # "Let's Go" flow
    artifact_template = models.JSONField(
        default=dict, blank=True, help_text="Template for artifact creation"
    )
    lets_go_inputs = models.JSONField(
        default=list,
        blank=True,
        help_text='Questions/inputs needed: [{"type": "text", "question": "..."}]',
    )

    # Evidence & artifacts
    evidence_url = models.URLField(
        max_length=500, blank=True, null=True, help_text="Proof of completion"
    )
    external_url = models.URLField(
        max_length=500,
        blank=True,
        null=True,
        help_text="LinkedIn profile, event link, course URL, etc.",
    )
    notes = models.JSONField(
        default=dict,
        blank=True,
        help_text="Additional context including milestone metadata and web search results",
    )

    # Day 1 Personalization Fields
    is_quick_win = models.BooleanField(
        default=False, help_text="< 30 min, high confidence task for Day 1 momentum"
    )
    task_category = models.CharField(
        max_length=20,
        choices=[
            ("quick_win", "Quick Win"),
            ("learning", "Learning"),
            ("foundation", "Foundation"),
            ("regular", "Regular"),
        ],
        default="regular",
        help_text="Task category for Day 1 personalization and UI display",
    )

    # Idempotency
    idempotency_key = models.CharField(
        max_length=100,
        blank=True,
        unique=True,
        null=True,
        help_text="Prevent duplicate creation",
    )

    # NEW: University-specific task fields
    university = models.ForeignKey(
        "university_database.University",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="todos",
        help_text="Associated university for this task",
    )

    requirement_type = models.CharField(
        max_length=50,
        choices=[
            ("eligibility_gap", "Eligibility Gap"),
            ("application", "Application Step"),
            ("document", "Document Preparation"),
            ("test", "Test Preparation"),
            ("foundation", "Foundation Preparation"),
            ("other", "Other"),
        ],
        default="other",
        db_index=True,
        help_text="Type of requirement for this task",
    )

    # Dedupe key for idempotent task generation
    dedupe_key = models.CharField(
        max_length=120,
        blank=True,
        db_index=True,
        help_text="Unique key to prevent duplicate tasks. REQUIRED for auto-generated tasks.",
    )

    reason = models.TextField(
        blank=True,
        default="",
        help_text="Example: 'University requires IELTS 7.5, you have 7.0'",
    )

    university_deadline = models.DateField(
        null=True, blank=True, help_text="Relevant deadline for this university's task"
    )

    # Optional: internal target date (deadline - buffer)
    due_date = models.DateField(
        null=True, blank=True, help_text="Internal target date for completing this task"
    )

    is_blocker = models.BooleanField(
        default=False, db_index=True, help_text="If true, this task blocks admission"
    )

    alternative_path = models.TextField(
        blank=True,
        default="",
        help_text="Suggested alternative (e.g., foundation program)",
    )

    is_auto_generated = models.BooleanField(
        default=False, help_text="True = generated by system, False = user-created"
    )

    # NEW: Requirement Engine fields
    requirement_key = models.CharField(
        max_length=100,
        blank=True,
        db_index=True,
        help_text="Requirement key from RequirementInstance (e.g., 'passport_validity', 'ielts_score')"
    )

    scope = models.CharField(
        max_length=20,
        choices=[
            ('global', 'Global'),  # Applies to all universities
            ('country', 'Country'),  # Country-specific (visa, medical, finance)
            ('university', 'University'),  # University-specific
            ('scholarship', 'Scholarship'),  # Scholarship-specific
        ],
        blank=True,
        db_index=True,
        help_text="Scope of this task",
    )

    stage = models.CharField(
        max_length=20,
        choices=[
            ('strategy', 'Strategy'),
            ('shortlist', 'Shortlist'),
            ('docs', 'Documents'),
            ('essays', 'Essays'),
            ('apply', 'Apply'),
            ('visa', 'Visa'),
            ('arrival', 'Post-Admission'),
        ],
        blank=True,
        db_index=True,
        help_text="Stage of the application process",
    )

    link_url = models.URLField(
        max_length=500,
        blank=True,
        help_text="URL to application portal or requirement page"
    )

    link_type = models.CharField(
        max_length=20,
        choices=[
            ('portal', 'Application Portal'),
            ('visa', 'Visa Requirements'),
            ('scholarship', 'Scholarship Info'),
            ('requirement_page', 'Official Requirement Page'),
            ('upload', 'Document Upload'),
            ('info', 'Information Page'),
        ],
        blank=True,
        help_text="Type of link",
    )

    evidence_fields = models.JSONField(
        default=list,
        blank=True,
        help_text="List of evidence fields required (uniform naming)",
    )

    evidence_status = models.CharField(
        max_length=20,
        choices=[
            ('missing', 'No evidence uploaded'),
            ('partial', 'Some evidence uploaded'),
            ('complete', 'All evidence uploaded'),
        ],
        default='missing',
        db_index=True,
        help_text="Status of evidence upload",
    )

    university_checklist = models.JSONField(
        default=dict,
        blank=True,
        help_text="Per-university checklist for global tasks {uni_id: {required, status, ...}}",
    )

    depends_on = models.JSONField(
        default=list,
        blank=True,
        help_text="List of dedupe_keys this task depends on",
    )

    country = models.CharField(
        max_length=100,
        blank=True,
        db_index=True,
        help_text="Country for country-specific tasks",
    )

    validation_status = models.CharField(
        max_length=20,
        choices=[
            ('pending', 'Pending Validation'),
            ('valid', 'Valid'),
            ('invalid', 'Invalid'),
            ('not_applicable', 'Not Applicable'),
        ],
        blank=True,
        help_text="Validation status for documents/essays",
    )

    # Scheduling
    scheduled_date = models.DateField()
    scheduled_time = models.TimeField(null=True, blank=True)
    source = models.CharField(
        max_length=20, choices=SOURCE_CHOICES, default="ai_generated"
    )

    # Status tracking
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="ready")
    completed_at = models.DateTimeField(null=True, blank=True)
    skipped_at = models.DateTimeField(null=True, blank=True)
    skip_reason = models.TextField(blank=True)

    # Notifications
    reminder_sent = models.BooleanField(default=False)
    reminder_time = models.DateTimeField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["scheduled_date", "priority", "created_at"]
        indexes = [
            models.Index(fields=["user", "scheduled_date", "status"]),
            models.Index(fields=["user", "university"]),
            models.Index(fields=["user", "is_blocker"]),
            models.Index(fields=["user", "is_auto_generated"]),
            models.Index(fields=["user", "dedupe_key"]),
            # NEW: Requirement engine indexes
            models.Index(fields=["user", "scope"]),
            models.Index(fields=["user", "stage"]),
            models.Index(fields=["user", "requirement_key"]),
            models.Index(fields=["user", "country"]),
            models.Index(fields=["user", "evidence_status"]),
        ]
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'dedupe_key'],
                condition=Q(dedupe_key__isnull=False) & ~Q(dedupe_key=''),
                name='unique_user_dedupe_key',
                violation_error_message='A task with this dedupe_key already exists for this user.'
            )
        ]
        # Note: SQLite doesn't enforce conditional unique constraints, but PostgreSQL does
        # Deduplication is enforced at both DB (PostgreSQL) and application level

    def __str__(self):
        return f"{self.user.email} - {self.title} ({self.scheduled_date})"

    @property
    def is_overdue(self):
        """Check if task is overdue"""
        if self.status in ["done", "skipped"]:
            return False
        return self.scheduled_date < timezone.now().date()

    @property
    def days_overdue(self):
        """Calculate days overdue"""
        if not self.is_overdue:
            return 0
        return (timezone.now().date() - self.scheduled_date).days

    def calculate_progress(self):
        """
        Calculate progress from Definition of Done + evidence
        Progress = weighted sum of completed DoD items + evidence bonus
        """
        if not self.definition_of_done:
            # Fallback: if no DoD, use simple status-based progress
            if self.status == "done":
                return 100
            elif self.status == "in_progress":
                return 50
            return 0

        total_weight = sum(item.get("weight", 0) for item in self.definition_of_done)
        if total_weight == 0:
            return 0

        completed_weight = sum(
            item.get("weight", 0)
            for item in self.definition_of_done
            if item.get("completed", False)
        )

        progress = int((completed_weight / total_weight) * 100)

        # Evidence bonus: +10% if evidence attached
        if self.evidence_url:
            progress = min(100, progress + 10)

        return progress

    def update_progress(self):
        """Update progress_percentage field"""
        self.progress_percentage = self.calculate_progress()
        self.save(update_fields=["progress_percentage"])

    def is_blocked(self):
        """Check if task is blocked by dependencies"""
        if not self.blocked_by:
            return False

        # Check if any blocker tasks are not done
        blocker_tasks = Todo.objects.filter(
            id__in=self.blocked_by, user=self.user
        ).exclude(status="done")

        return blocker_tasks.exists()

    def unlock_dependents(self):
        """When this task completes, unlock dependent tasks"""
        if not self.unlocks:
            return

        dependent_tasks = Todo.objects.filter(id__in=self.unlocks, user=self.user)

        for task in dependent_tasks:
            if not task.is_blocked():
                task.status = "ready"
                task.save(update_fields=["status"])


# Import artifact models to make them discoverable by Django
# Import advanced task models
from .advanced_models import (
    AIInsight,
    RecurringTaskTemplate,
    TaskCompletion,
    TaskConversation,
)
from .artifact_models import (
    AutomationAudit,
    AutomationConsent,
    TaskArtifact,
    TaskEvidence,
    TaskRun,
)

# Import essay models
from .essay_models import EssayFeedback, EssayProject, EssayTemplate
