# Generated by Django 5.2.10 on 2026-02-10 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university_database', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_snapshot', models.JSONField(help_text='Profile data at the time of recommendation')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_recommendations', models.IntegerField(help_text='Total number of universities recommended')),
                ('filter_count', models.IntegerField(help_text='Number of universities after filtering')),
                ('llm_reranked', models.BooleanField(default=False, help_text='Whether LLM reranking was applied')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recommendation Log',
                'verbose_name_plural': 'Recommendation Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(help_text='Position in results (1-indexed)')),
                ('fit_score', models.IntegerField(help_text='Fit score (0-100) - how well university matches preferences')),
                ('chance_score', models.IntegerField(help_text='Chance score (0-100) - how likely admission is')),
                ('finance_score', models.IntegerField(help_text='Finance score (0-100) - how feasible paying is')),
                ('final_rank_score', models.IntegerField(help_text='Final ranking score (0-100)')),
                ('llm_fit_score', models.IntegerField(blank=True, help_text='LLM-assessed fit score', null=True)),
                ('llm_confidence', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20, null=True)),
                ('llm_reasons', models.JSONField(default=list, help_text='LLM-generated reasons for fit')),
                ('llm_risks', models.JSONField(default=list, help_text='LLM-generated risks/concerns')),
                ('llm_why_not_fit', models.JSONField(default=list, help_text='LLM-generated reasons why not a good fit')),
                ('llm_missing_info', models.JSONField(default=list, help_text='LLM-generated missing info gaps')),
                ('llm_next_actions', models.JSONField(default=list, help_text='LLM-generated suggested next actions')),
                ('bucket', models.CharField(choices=[('Reach', 'Reach'), ('Match', 'Match'), ('Safety', 'Safety')], help_text='Admissions likelihood category', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_database.university')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='university_recommender.recommendationlog')),
            ],
            options={
                'verbose_name': 'Recommendation Item',
                'verbose_name_plural': 'Recommendation Items',
                'ordering': ['log', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='UniversityShortlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='User notes about this university')),
                ('status', models.CharField(choices=[('researching', 'Researching'), ('applying', 'Applying'), ('applied', 'Applied'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted')], default='researching', max_length=20)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_database.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_shortlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'University Shortlist',
                'verbose_name_plural': 'University Shortlists',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('shortlisted', 'Shortlisted'), ('removed', 'Removed'), ('bucket_changed', 'Bucket Changed'), ('applied', 'Applied'), ('ignored', 'Ignored')], max_length=20)),
                ('new_bucket', models.CharField(blank=True, choices=[('Reach', 'Reach'), ('Match', 'Match'), ('Safety', 'Safety')], help_text='New bucket if user changed it', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, help_text='User notes on feedback')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='university_recommender.recommendationitem')),
            ],
            options={
                'verbose_name': 'Recommendation Feedback',
                'verbose_name_plural': 'Recommendation Feedbacks',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['item', 'action'], name='university__item_id_bfd4e1_idx'), models.Index(fields=['-timestamp'], name='university__timesta_c1893a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='recommendationlog',
            index=models.Index(fields=['user', '-timestamp'], name='university__user_id_5f2bb8_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationlog',
            index=models.Index(fields=['-timestamp'], name='university__timesta_4e4f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationitem',
            index=models.Index(fields=['log', 'rank'], name='university__log_id_f04b64_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationitem',
            index=models.Index(fields=['university', 'bucket'], name='university__univers_7cafe0_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationitem',
            index=models.Index(fields=['-created_at'], name='university__created_af9569_idx'),
        ),
        migrations.AddIndex(
            model_name='universityshortlist',
            index=models.Index(fields=['user', '-added_at'], name='university__user_id_6cc381_idx'),
        ),
        migrations.AddIndex(
            model_name='universityshortlist',
            index=models.Index(fields=['user', 'status'], name='university__user_id_78fcfa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='universityshortlist',
            unique_together={('user', 'university')},
        ),
    ]
