# Generated by Django 5.2.10 on 2026-02-18 18:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todos', '0017_add_essay_models'),
        ('users', '0019_userprofile_activity_visibility_userprofile_bio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('bio', models.TextField(max_length=1000)),
                ('photo_url', models.URLField(blank=True)),
                ('education', models.CharField(blank=True, max_length=300)),
                ('expertise_areas', models.JSONField(default=list)),
                ('hourly_rate_credits', models.IntegerField(default=0)),
                ('timezone', models.CharField(default='America/New_York', max_length=63)),
                ('meeting_link', models.URLField(blank=True, help_text='Google Meet/Zoom link (V1)')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_sessions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentor Profile',
                'verbose_name_plural': 'Mentor Profiles',
            },
        ),
        migrations.CreateModel(
            name='MentorBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at_utc', models.DateTimeField()),
                ('end_at_utc', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(choices=[(15, '15 min'), (30, '30 min'), (45, '45 min'), (60, '60 min')], validators=[django.core.validators.MinValueValidator(15)])),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('student_notes', models.TextField(blank=True)),
                ('meeting_url', models.URLField(blank=True)),
                ('mentor_summary', models.TextField(blank=True)),
                ('action_items', models.JSONField(blank=True, default=list)),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_bookings', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='mentorship.mentorprofile')),
            ],
            options={
                'verbose_name': 'Mentor Booking',
                'verbose_name_plural': 'Mentor Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorAvailabilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('start_minute', models.IntegerField()),
                ('end_minute', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to='mentorship.mentorprofile')),
            ],
            options={
                'verbose_name': 'Mentor Availability Rule',
                'verbose_name_plural': 'Mentor Availability Rules',
            },
        ),
        migrations.CreateModel(
            name='MentorReviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('plan', 'Plan Review'), ('essay', 'Essay Review')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('done', 'Done')], default='pending', max_length=20)),
                ('student_questions', models.TextField(blank=True)),
                ('price_credits', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('essay_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to='todos.essayproject')),
                ('goal_spec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to='users.goalspec')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to='mentorship.mentorprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentor Review Request',
                'verbose_name_plural': 'Mentor Review Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorReviewResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_comment', models.TextField()),
                ('payload_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='mentorship.mentorreviewrequest')),
            ],
            options={
                'verbose_name': 'Mentor Review Response',
                'verbose_name_plural': 'Mentor Review Responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mentorprofile',
            index=models.Index(fields=['is_verified', 'is_active'], name='mentorship__is_veri_0a6698_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorprofile',
            index=models.Index(fields=['rating'], name='mentorship__rating_f6cd70_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorbooking',
            index=models.Index(fields=['mentor', 'start_at_utc'], name='mentorship__mentor__bb0a0b_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorbooking',
            index=models.Index(fields=['student', '-created_at'], name='mentorship__student_12eab8_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorbooking',
            index=models.Index(fields=['status', 'start_at_utc'], name='mentorship__status_cdd3a9_idx'),
        ),
        migrations.AddIndex(
            model_name='mentoravailabilityrule',
            index=models.Index(fields=['mentor', 'day_of_week', 'is_active'], name='mentorship__mentor__1d2e0d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mentoravailabilityrule',
            unique_together={('mentor', 'day_of_week', 'start_minute')},
        ),
        migrations.AddIndex(
            model_name='mentorreviewrequest',
            index=models.Index(fields=['mentor', 'status'], name='mentorship__mentor__5aeed4_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorreviewrequest',
            index=models.Index(fields=['student', '-created_at'], name='mentorship__student_28b8af_idx'),
        ),
    ]
