# Generated by Django 5.2.10 on 2026-03-16 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0002_add_verification_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Deprecated: Use verification_status instead'),
        ),
        migrations.AddIndex(
            model_name='mentorprofile',
            index=models.Index(fields=['verification_status'], name='mentorship__verific_91e809_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorprofile',
            index=models.Index(fields=['flag_count'], name='mentorship__flag_co_ab6c7c_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorprofile',
            index=models.Index(fields=['verification_status', 'is_active'], name='mentorship__verific_45a52f_idx'),
        ),
    ]
