# Generated by Django 6.0.3 on 2026-03-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0003_alter_mentorprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorbooking',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Whether 15-min reminder notification has been sent'),
        ),
    ]
