# Generated by Django 5.1.5 on 2025-10-15 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_todo_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='external_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile, event link, course URL, etc.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional context from web search results'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='source',
            field=models.CharField(choices=[('ai_generated', 'AI Generated'), ('user_added', 'User Added'), ('integrated', 'AI Integrated'), ('ai_agent', 'AI Agent')], default='ai_generated', max_length=20),
        ),
    ]
