# Generated by Django 5.1.5 on 2025-10-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_automationconsent_taskartifact_automationaudit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('in_progress', 'In Progress'), ('done', 'Done'), ('skipped', 'Skipped'), ('blocked', 'Blocked')], default='ready', max_length=20),
        ),
    ]
