# Generated by Django 5.1.5 on 2025-10-17 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_alter_todo_status'),
        ('users', '0005_goalspec_category_goalspec_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='goalspec',
            field=models.ForeignKey(blank=True, help_text='Associated goal specification from new onboarding', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='users.goalspec'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='source',
            field=models.CharField(choices=[('ai_generated', 'AI Generated'), ('user_added', 'User Added'), ('integrated', 'AI Integrated'), ('ai_agent', 'AI Agent'), ('daily_planner', 'Daily Planner'), ('web_research', 'Web Research')], default='ai_generated', max_length=20),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('in_progress', 'In Progress'), ('done', 'Done'), ('skipped', 'Skipped'), ('blocked', 'Blocked')], default='ready', max_length=20),
        ),
    ]
