# Generated by Django 5.1.5 on 2025-10-18 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_todo_goalspec_alter_todo_source_alter_todo_status'),
        ('users', '0005_goalspec_category_goalspec_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='cognitive_load',
            field=models.IntegerField(default=3, help_text='Mental effort required (1=trivial, 5=intense focus)'),
        ),
        migrations.AddField(
            model_name='todo',
            name='contribution_weight',
            field=models.FloatField(default=1.0, help_text="Weight of this task's contribution to parent goal (0.0-1.0)"),
        ),
        migrations.AddField(
            model_name='todo',
            name='energy_level',
            field=models.CharField(choices=[('high', 'High Energy'), ('medium', 'Medium'), ('low', 'Low Energy')], default='medium', help_text='Required energy level for this task', max_length=20),
        ),
        migrations.AddField(
            model_name='todo',
            name='estimated_energy_cost',
            field=models.IntegerField(default=50, help_text='Combined metric: timebox * cognitive_load (0-300)'),
        ),
        migrations.AddField(
            model_name='todo',
            name='task_level',
            field=models.CharField(choices=[('goal', 'Goal'), ('sub_goal', 'Sub-goal'), ('action', 'Action')], default='action', help_text='Hierarchy level: goal → sub_goal → action', max_length=20),
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('category_progress', 'Category Progress'), ('skip_pattern', 'Skip Pattern'), ('opportunity', 'New Opportunity'), ('milestone_suggestion', 'Milestone Suggestion'), ('time_pattern', 'Time Pattern'), ('energy_mismatch', 'Energy Mismatch'), ('overload_warning', 'Overload Warning'), ('success_celebration', 'Success Celebration')], max_length=30)),
                ('category', models.CharField(blank=True, help_text='Related goal category (study/career/sport/etc)', max_length=20, null=True)),
                ('title', models.CharField(help_text='Short insight title', max_length=200)),
                ('message', models.TextField(help_text='Full insight message')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Supporting data (charts, stats, etc)')),
                ('action_suggestions', models.JSONField(blank=True, default=list, help_text='\n        Actionable suggestions: [\n            {"action": "reschedule_to_morning", "task_ids": [1,2,3]},\n            {"action": "reduce_daily_tasks", "from": 10, "to": 7}\n        ]\n        ')),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('action_taken', models.BooleanField(default=False, help_text='Did user act on this insight?')),
                ('priority', models.IntegerField(default=2, help_text='1=low, 2=medium, 3=high')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this insight becomes irrelevant', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='todos_aiins_user_id_bb6260_idx'), models.Index(fields=['is_read', 'is_dismissed'], name='todos_aiins_is_read_2c09f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecurringTaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Task title template', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Task description template')),
                ('task_type', models.CharField(default='manual', max_length=20)),
                ('task_level', models.CharField(default='sub_goal', max_length=20)),
                ('energy_level', models.CharField(default='medium', max_length=20)),
                ('cognitive_load', models.IntegerField(default=2)),
                ('timebox_minutes', models.IntegerField(default=30)),
                ('priority', models.IntegerField(default=2)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Every 2 Weeks'), ('monthly', 'Monthly')], help_text='How often to generate this task', max_length=20)),
                ('schedule_day', models.CharField(blank=True, choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], help_text='For weekly/biweekly: which day of week', max_length=10, null=True)),
                ('schedule_time', models.TimeField(blank=True, help_text='Preferred time of day', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether to continue generating tasks')),
                ('next_generation_date', models.DateField(help_text='Next date to generate task')),
                ('last_generated_at', models.DateTimeField(blank=True, help_text='Last time task was generated', null=True)),
                ('total_generated', models.IntegerField(default=0, help_text='Total number of tasks generated from this template')),
                ('suggested_by_ai', models.BooleanField(default=False, help_text='Was this template suggested by AI?')),
                ('ai_confidence', models.FloatField(blank=True, help_text='AI confidence in this suggestion (0.0-1.0)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goalspec', models.ForeignKey(blank=True, help_text='Associated goal specification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_templates', to='users.goalspec')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_generation_date', '-is_active'],
                'indexes': [models.Index(fields=['user', 'is_active', 'next_generation_date'], name='todos_recur_user_id_c04825_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('actual_duration_minutes', models.IntegerField(blank=True, help_text='How long it actually took', null=True)),
                ('difficulty_rating', models.IntegerField(blank=True, choices=[(1, 'Very Easy'), (2, 'Easy'), (3, 'Medium'), (4, 'Hard'), (5, 'Very Hard')], help_text="User's subjective difficulty rating", null=True)),
                ('completion_reason', models.CharField(choices=[('completed', 'Successfully Completed'), ('skipped_no_time', 'Skipped - No Time'), ('skipped_no_motivation', 'Skipped - No Motivation'), ('skipped_distracted', 'Skipped - Got Distracted'), ('skipped_overestimated', 'Skipped - Overestimated Difficulty'), ('skipped_blocked', 'Skipped - Blocked by Dependencies'), ('skipped_other', 'Skipped - Other Reason')], default='completed', max_length=30)),
                ('time_of_day', models.CharField(blank=True, help_text='morning/afternoon/evening/night', max_length=20, null=True)),
                ('energy_level_at_completion', models.CharField(blank=True, help_text="User's energy level when completing (high/medium/low)", max_length=20, null=True)),
                ('notes', models.TextField(blank=True, help_text="User's additional notes")),
                ('would_reschedule_to', models.CharField(blank=True, help_text='If could redo, when would user schedule this?', max_length=20, null=True)),
                ('analyzed_by_ai', models.BooleanField(default=False, help_text='Has AI processed this feedback?')),
                ('ai_insights', models.JSONField(blank=True, default=dict, help_text='AI-generated insights from this completion')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_feedback', to='todos.todo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['user', '-completed_at'], name='todos_taskc_user_id_709c62_idx'), models.Index(fields=['completion_reason'], name='todos_taskc_complet_fd628f_idx')],
            },
        ),
    ]
