# Generated by Django 5.1.5 on 2025-10-19 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0009_todo_cognitive_load_todo_contribution_weight_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text="User's question")),
                ('answer', models.TextField(help_text="AI's response")),
                ('mode', models.CharField(choices=[('clarify', 'Clarify'), ('expand', 'Expand'), ('research', 'Research')], default='clarify', help_text='AI mode used for this response', max_length=20)),
                ('links', models.JSONField(blank=True, default=list, help_text='Links provided in response')),
                ('contacts', models.JSONField(blank=True, default=list, help_text='Contacts provided in response')),
                ('steps', models.JSONField(blank=True, default=list, help_text='Steps provided in response')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('was_expanded', models.BooleanField(default=False, help_text='Was this question expanded from clarify to research?')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='todos.todo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['task', 'created_at'], name='todos_taskc_task_id_7a7b3a_idx'), models.Index(fields=['user', '-created_at'], name='todos_taskc_user_id_ee860e_idx')],
            },
        ),
    ]
