# Generated by Django 5.1.5 on 2025-11-12 18:43

from django.db import migrations
import json


def convert_notes_to_json(apps, schema_editor):
    """
    Convert existing string notes to JSON format.

    - If notes is empty string, set to {}
    - If notes looks like JSON, try to parse it
    - Otherwise, wrap string in {"text": "..."}
    """
    Todo = apps.get_model('todos', 'Todo')

    for todo in Todo.objects.all():
        if not todo.notes:
            # Empty string → empty dict
            todo.notes = '{}'
        elif todo.notes.strip().startswith('{'):
            # Already looks like JSON, validate it
            try:
                json.loads(todo.notes)
                # Valid JSON, keep as is
            except json.JSONDecodeError:
                # Invalid JSON, wrap in object
                todo.notes = json.dumps({'text': todo.notes})
        else:
            # Plain string, wrap in {"text": "..."}
            todo.notes = json.dumps({'text': todo.notes})

        todo.save(update_fields=['notes'])


def reverse_conversion(apps, schema_editor):
    """
    Reverse migration: Convert JSON back to string.
    """
    Todo = apps.get_model('todos', 'Todo')

    for todo in Todo.objects.all():
        if todo.notes == '{}':
            todo.notes = ''
        else:
            try:
                data = json.loads(todo.notes)
                if isinstance(data, dict) and 'text' in data:
                    todo.notes = data['text']
                else:
                    # Keep as JSON string
                    pass
            except json.JSONDecodeError:
                pass

        todo.save(update_fields=['notes'])


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0011_todo_is_quick_win_todo_task_category'),
    ]

    operations = [
        migrations.RunPython(convert_notes_to_json, reverse_conversion),
    ]
