# Generated by Django 5.1.5 on 2025-11-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0012_convert_notes_to_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='notes',
            field=models.JSONField(blank=True, default=dict, help_text='Additional context including milestone metadata and web search results'),
        ),
    ]
