# Generated by Django 5.1.5 on 2026-01-21 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('premium', 'Premium')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_yearly', models.DecimalField(decimal_places=2, max_digits=6)),
                ('features', models.JSONField(default=list, help_text='List of feature strings')),
                ('stripe_price_id_monthly', models.CharField(blank=True, max_length=100)),
                ('stripe_price_id_yearly', models.CharField(blank=True, max_length=100)),
                ('is_popular', models.BooleanField(default=False, help_text='Mark as most popular')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('monthly_video_calls', models.IntegerField(default=0, help_text='Number of video calls per month')),
                ('monthly_text_questions', models.IntegerField(default=0, help_text='Number of text questions per month')),
                ('dedicated_mentor', models.BooleanField(default=False, help_text='Whether user gets a dedicated mentor')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExtracurricularActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('leadership', 'Leadership'), ('academic', 'Academic'), ('sports', 'Sports'), ('arts', 'Arts'), ('community_service', 'Community Service'), ('work', 'Work Experience'), ('entrepreneurship', 'Entrepreneurship'), ('technology', 'Technology'), ('research', 'Research'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_ongoing', models.BooleanField(default=False)),
                ('hours_per_week', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('achievements', models.TextField(blank=True, help_text='Notable achievements, impact, results')),
                ('leadership_role', models.BooleanField(default=False, help_text='Whether user held leadership position')),
                ('priority_order', models.IntegerField(default=0, help_text="User's priority ranking")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracurriculars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extracurricular Activity',
                'verbose_name_plural': 'Extracurricular Activities',
                'ordering': ['priority_order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(help_text='Step number (0-13)')),
                ('data', models.JSONField(default=dict, help_text='Data collected at this step')),
                ('time_spent_seconds', models.IntegerField(default=0, help_text='Time spent on this step')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Onboarding Snapshot',
                'verbose_name_plural': 'Onboarding Snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.IntegerField(default=0, help_text='Current step (0-13)')),
                ('completed_steps', models.JSONField(default=list, help_text='List of completed step numbers')),
                ('data', models.JSONField(default=dict, help_text='All onboarding data collected')),
                ('selected_language', models.CharField(default='en', help_text='Selected language code', max_length=10)),
                ('is_onboarding_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='structured_onboarding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Onboarding State',
                'verbose_name_plural': 'Onboarding States',
            },
        ),
        migrations.CreateModel(
            name='TargetUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=200)),
                ('university_slug', models.SlugField(max_length=100)),
                ('category', models.CharField(choices=[('reach', 'Reach'), ('target', 'Target'), ('safety', 'Safety')], max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('acceptance_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avg_sat', models.IntegerField(blank=True, null=True)),
                ('avg_act', models.IntegerField(blank=True, null=True)),
                ('tuition_per_year', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('major', models.CharField(max_length=100)),
                ('why_suggested', models.TextField(blank=True, help_text='AI reasoning for suggestion')),
                ('is_ai_suggested', models.BooleanField(default=True)),
                ('is_selected', models.BooleanField(default=True, help_text='User selected this university')),
                ('priority_order', models.IntegerField(default=0, help_text="User's priority ranking")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_universities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Target University',
                'verbose_name_plural': 'Target Universities',
                'ordering': ['priority_order', 'category'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('canceled', 'Canceled'), ('past_due', 'Past Due'), ('incomplete', 'Incomplete')], default='incomplete', max_length=20)),
                ('stripe_subscription_id', models.CharField(max_length=100, unique=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('remaining_video_calls', models.IntegerField(default=0)),
                ('remaining_text_questions', models.IntegerField(default=0)),
                ('promo_code_used', models.CharField(blank=True, max_length=50)),
                ('discount_percentage', models.IntegerField(default=0, help_text='Discount percentage applied')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor_assigned', models.ForeignKey(blank=True, help_text='Assigned mentor for Pro/Premium users', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_users', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='onboarding.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
            },
        ),
    ]
