# Generated by Django mentor booking paywall implementation

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='monthly_mentor_bookings',
            field=models.IntegerField(default=0, help_text='Number of mentor session bookings per month'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='remaining_mentor_bookings',
            field=models.IntegerField(default=0, help_text='Remaining mentor bookings this month'),
        ),
    ]
