# Generated by Django 5.2.10 on 2026-02-10 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversitySeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.FloatField(help_text="Student's GPA")),
                ('gpa_scale', models.CharField(choices=[('4.0', '4.0 scale'), ('5.0', '5.0 scale'), ('100', '100 point scale')], default='4.0', max_length=10)),
                ('sat_score', models.IntegerField(blank=True, help_text='SAT total score (1600 max)', null=True)),
                ('sat_english', models.IntegerField(blank=True, null=True)),
                ('sat_math', models.IntegerField(blank=True, null=True)),
                ('act_score', models.IntegerField(blank=True, help_text='ACT composite score (36 max)', null=True)),
                ('toefl_score', models.IntegerField(blank=True, help_text='TOEFL score (120 max)', null=True)),
                ('ielts_score', models.FloatField(blank=True, help_text='IELTS score (9.0 max)', null=True)),
                ('duolingo_score', models.IntegerField(blank=True, help_text='Duolingo English Test (160 max)', null=True)),
                ('course_rigor', models.CharField(choices=[('ap_ib_ib_plus', 'AP+IB+ (Most Rigorous)'), ('ap_ib', 'AP or IB'), ('honors', 'Honors'), ('regular', 'Regular')], default='regular', max_length=20)),
                ('ap_courses', models.JSONField(default=list, help_text='List of AP courses with scores')),
                ('ib_courses', models.JSONField(default=list, help_text='List of IB courses')),
                ('academic_competitions', models.JSONField(default=list, help_text='List of academic competitions and awards')),
                ('country', models.CharField(help_text='Country of residence', max_length=100)),
                ('citizenship', models.CharField(help_text='Citizenship country', max_length=100)),
                ('budget_currency', models.CharField(default='USD', help_text='USD, EUR, GBP, etc.', max_length=3)),
                ('max_budget', models.IntegerField(blank=True, help_text='Maximum budget per year in currency', null=True)),
                ('financial_need', models.CharField(choices=[('full_ride', 'Full ride needed'), ('significant', 'Significant aid needed'), ('moderate', 'Moderate aid helpful'), ('none', 'No aid needed')], default='none', max_length=50)),
                ('need_blind_preference', models.BooleanField(default=False, help_text='Prefer schools with need-blind admissions')),
                ('merit_aid_required', models.BooleanField(default=False, help_text='Require schools with merit aid opportunities')),
                ('intended_major_1', models.CharField(help_text='Primary intended major', max_length=100)),
                ('intended_major_2', models.CharField(blank=True, help_text='Secondary intended major', max_length=100)),
                ('intended_major_3', models.CharField(blank=True, help_text='Tertiary intended major', max_length=100)),
                ('academic_interests', models.TextField(blank=True, help_text='Free text explaining academic interests and why')),
                ('preferred_size', models.CharField(blank=True, choices=[('small', 'Small (< 5,000 students)'), ('medium', 'Medium (5,000 - 15,000 students)'), ('large', 'Large (> 15,000 students)')], max_length=50)),
                ('preferred_location', models.CharField(blank=True, choices=[('urban', 'Urban'), ('suburban', 'Suburban'), ('rural', 'Rural')], max_length=50)),
                ('preferred_region', models.CharField(blank=True, help_text='northeast, midwest, etc.', max_length=100)),
                ('weather_preference', models.CharField(blank=True, max_length=50)),
                ('target_countries', models.JSONField(default=list, help_text='List of countries to target for university applications')),
                ('excluded_universities', models.JSONField(default=list, help_text='List of university short_names to exclude')),
                ('test_optional_flexible', models.BooleanField(default=False, help_text='Flexible about test-optional schools')),
                ('early_decision_willing', models.BooleanField(default=False, help_text='Willing to apply Early Decision')),
                ('early_action_willing', models.BooleanField(default=True, help_text='Willing to apply Early Action')),
                ('spike_area', models.CharField(blank=True, choices=[('research_olympiad', 'Research/Olympiad'), ('athletics', 'Athletics (Recruited)'), ('arts', 'Arts'), ('leadership', 'Leadership'), ('other', 'Other')], max_length=100)),
                ('spike_achievement', models.TextField(blank=True, help_text='Description of exceptional achievement in spike area')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='university_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'University Seeker Profile',
                'verbose_name_plural': 'University Seeker Profiles',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtracurricularActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('leadership', 'Leadership'), ('research', 'Research'), ('volunteering', 'Volunteering'), ('sports', 'Sports'), ('arts', 'Arts'), ('work', 'Work Experience'), ('academic', 'Academic Club'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(help_text='Activity name', max_length=200)),
                ('role', models.CharField(help_text="Student's role/title", max_length=100)),
                ('hours_per_week', models.IntegerField(help_text='Hours spent per week')),
                ('weeks_per_year', models.IntegerField(help_text='Weeks participated per year')),
                ('years_participated', models.IntegerField(help_text='Number of years participated')),
                ('impact_level', models.CharField(choices=[('low', 'Low - School level only'), ('medium', 'Medium - Local/District level'), ('high', 'High - State/Regional level'), ('national', 'National level'), ('international', 'International level')], default='medium', max_length=20)),
                ('leadership_position', models.BooleanField(default=False, help_text='Was this a leadership position? (President, Captain, etc.)')),
                ('achievements', models.TextField(blank=True, help_text='Description of achievements')),
                ('achievements_impact', models.CharField(blank=True, choices=[('school', 'School level'), ('state', 'State/Regional level'), ('national', 'National level'), ('international', 'International level')], help_text='Level of achievements', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracurriculars', to='university_profile.universityseekerprofile')),
            ],
            options={
                'verbose_name': 'Extracurricular Activity',
                'verbose_name_plural': 'Extracurricular Activities',
                'ordering': ['-years_participated', '-hours_per_week'],
            },
        ),
    ]
