# Generated by Django 5.2.10 on 2026-02-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityseekerprofile',
            name='current_grade_level',
            field=models.CharField(blank=True, choices=[('grade_9', 'Grade 9'), ('grade_10', 'Grade 10'), ('grade_11', 'Grade 11'), ('grade_12', 'Grade 12'), ('graduated', 'Graduated'), ('gap_year', 'Gap Year')], help_text='Current grade level', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='universityseekerprofile',
            name='education_system',
            field=models.CharField(choices=[('11_year', '11-year system (Russia/CIS)'), ('12_year', '12-year system (US/UK)'), ('ib', 'IB Diploma'), ('a_level', 'A-Level'), ('ap', 'AP'), ('foundation', 'Foundation completed'), ('other', 'Other')], default='other', help_text='Current or completed education system', max_length=50),
        ),
        migrations.AddField(
            model_name='universityseekerprofile',
            name='graduation_year',
            field=models.IntegerField(blank=True, help_text='Expected or actual graduation year', null=True),
        ),
        migrations.AddField(
            model_name='universityseekerprofile',
            name='tests_completed',
            field=models.JSONField(blank=True, default=dict, help_text="Completed tests with scores and dates: {sat: {score: 1200, date: '2024-01'}, ielts: {score: 7.0, date: '2024-02'}}"),
        ),
    ]
