# Generated by Django 5.2.10 on 2026-02-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_profile', '0002_universityseekerprofile_current_grade_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityseekerprofile',
            name='education_path_strategy',
            field=models.CharField(blank=True, choices=[('direct', 'Direct Application'), ('foundation', 'Foundation Year'), ('change_shortlist', 'Change Shortlist')], default='', help_text="User's chosen path for education system mismatches. Empty = not chosen yet", max_length=30),
        ),
        migrations.AddField(
            model_name='universityseekerprofile',
            name='eligibility_checked_at',
            field=models.DateTimeField(blank=True, help_text='Last time eligibility was checked', null=True),
        ),
        migrations.AddField(
            model_name='universityseekerprofile',
            name='ielts_date',
            field=models.DateField(blank=True, help_text='Date IELTS test was taken', null=True),
        ),
        migrations.AddField(
            model_name='universityseekerprofile',
            name='ielts_listening_score',
            field=models.FloatField(blank=True, help_text='IELTS Listening score (9.0 max)', null=True),
        ),
        migrations.AddField(
            model_name='universityseekerprofile',
            name='ielts_reading_score',
            field=models.FloatField(blank=True, help_text='IELTS Reading score (9.0 max)', null=True),
        ),
        migrations.AddField(
            model_name='universityseekerprofile',
            name='ielts_speaking_score',
            field=models.FloatField(blank=True, help_text='IELTS Speaking score (9.0 max)', null=True),
        ),
        migrations.AddField(
            model_name='universityseekerprofile',
            name='ielts_type',
            field=models.CharField(blank=True, choices=[('academic', 'Academic'), ('general', 'General Training')], help_text='IELTS test type', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='universityseekerprofile',
            name='ielts_writing_score',
            field=models.FloatField(blank=True, help_text='IELTS Writing score (9.0 max)', null=True),
        ),
        migrations.AddField(
            model_name='universityseekerprofile',
            name='overall_eligibility_status',
            field=models.CharField(blank=True, choices=[('eligible', 'Eligible'), ('partially_eligible', 'Partially Eligible'), ('not_eligible', 'Not Eligible'), ('', 'Not Checked')], default='', help_text='Overall eligibility status across shortlist', max_length=20),
        ),
        migrations.AlterField(
            model_name='universityseekerprofile',
            name='education_system',
            field=models.CharField(blank=True, choices=[('11_year', '11-year system (Russia/CIS)'), ('12_year', '12-year system (US/UK)'), ('ib', 'IB Diploma'), ('a_level', 'A-Level'), ('ap', 'AP'), ('foundation', 'Foundation completed'), ('other', 'Other')], default='', help_text='Current or completed education system. Empty = not provided', max_length=50),
        ),
    ]
