# Generated by Django 5.2.10 on 2026-02-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_profile', '0003_universityseekerprofile_education_path_strategy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityseekerprofile',
            name='additional_context',
            field=models.TextField(blank=True, help_text='Additional context, achievements, or circumstances not captured elsewhere (for personalized planning)'),
        ),
    ]
