from django.db import models
from django.conf import settings
from django.utils import timezone


class UserBehaviorPattern(models.Model):
    """
    Stores aggregated user behavior patterns for reflection generation

    Examples:
    - failure_time: User fails/skips tasks scheduled in evening
    - failure_category: User skips 'career' tasks 60% of the time
    - procrastination: 'study' tasks delayed by 3+ days on average
    - chat_topics: User discusses 'interview prep' frequently
    """
    PATTERN_TYPE_CHOICES = [
        ('failure_time', 'Failure Time Pattern'),
        ('failure_category', 'Failure Category Pattern'),
        ('procrastination', 'Procrastination Pattern'),
        ('chat_topics', 'Chat Topics Pattern'),
    ]

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='behavior_patterns'
    )

    pattern_type = models.CharField(
        max_length=30,
        choices=PATTERN_TYPE_CHOICES,
        help_text="Type of behavior pattern detected"
    )

    # Time window for this pattern
    time_window_start = models.DateField(
        help_text="Start date of analyzed period"
    )
    time_window_end = models.DateField(
        help_text="End date of analyzed period"
    )

    # Pattern data (flexible JSON structure)
    data = models.JSONField(
        default=dict,
        help_text="""
        Pattern-specific data:
        failure_time: {"time_slot": "evening", "failure_rate": 0.7, "tasks_affected": 5}
        failure_category: {"category": "career", "failure_rate": 0.6, "total_tasks": 10}
        procrastination: {"category": "study", "avg_delay_days": 3.5, "tasks_count": 8}
        chat_topics: {"topic": "interview prep", "frequency": 12, "sentiment": "anxious"}
        """
    )

    # AI confidence in this pattern (0.0 - 1.0)
    confidence_score = models.FloatField(
        default=0.5,
        help_text="AI confidence in this pattern (0.0-1.0)"
    )

    # Pattern lifecycle
    first_detected = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(
        default=True,
        help_text="Whether this pattern is still relevant"
    )

    class Meta:
        ordering = ['-confidence_score', '-last_updated']
        indexes = [
            models.Index(fields=['user', 'pattern_type', 'is_active']),
            models.Index(fields=['time_window_start', 'time_window_end']),
        ]
        unique_together = ['user', 'pattern_type', 'time_window_start']

    def __str__(self):
        return f"{self.user.email} - {self.pattern_type} ({self.confidence_score:.2f})"


class WeeklyReflection(models.Model):
    """
    Stores generated weekly reflections for users

    Generated every Sunday evening and on-demand
    Displayed in: Push notifications, Insights tab, Chat messages
    """
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='weekly_reflections'
    )

    # Week period
    week_start_date = models.DateField(
        help_text="Monday of the week"
    )
    week_end_date = models.DateField(
        help_text="Sunday of the week"
    )

    # Generated insights
    insights = models.JSONField(
        default=list,
        help_text="""
        Array of insights: [
            {
                "type": "failure_pattern",
                "icon": "🔴",
                "message": "You skipped career tasks 3 times - all scheduled in evening",
                "evidence": {"tasks": [1, 2, 3], "category": "career", "time": "evening"},
                "priority": 3
            },
            {
                "type": "chat_topic",
                "icon": "💬",
                "message": "Most discussed: interview prep (5 times)",
                "evidence": {"topic": "interview prep", "count": 5},
                "priority": 2
            }
        ]
        """
    )

    # Action items suggested by AI
    action_items = models.JSONField(
        default=list,
        help_text="""
        Array of actionable suggestions: [
            {
                "action": "reschedule_tasks",
                "description": "Move career tasks to morning (9-11am)",
                "task_ids": [1, 2, 3],
                "impact": "high"
            },
            {
                "action": "create_recurring",
                "description": "Add recurring 'Interview prep' task every Tuesday",
                "impact": "medium"
            }
        ]
        """
    )

    # Full reflection message (adaptive format)
    full_message = models.TextField(
        help_text="Complete reflection message generated by AI"
    )

    # Status
    is_read = models.BooleanField(default=False)
    notified_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When push notification was sent"
    )
    shown_in_chat = models.BooleanField(
        default=False,
        help_text="Whether reflection was shown in chat"
    )

    # Generation metadata
    generated_at = models.DateTimeField(auto_now_add=True)
    patterns_analyzed = models.IntegerField(
        default=0,
        help_text="Number of behavior patterns analyzed"
    )
    generation_method = models.CharField(
        max_length=20,
        choices=[
            ('scheduled', 'Scheduled (Sunday)'),
            ('on_demand', 'On Demand (User Request)'),
        ],
        default='scheduled'
    )

    class Meta:
        ordering = ['-week_start_date']
        indexes = [
            models.Index(fields=['user', '-week_start_date']),
            models.Index(fields=['is_read']),
        ]
        unique_together = ['user', 'week_start_date']

    def __str__(self):
        return f"{self.user.email} - Week {self.week_start_date.strftime('%Y-%m-%d')}"

    def mark_as_read(self):
        """Mark reflection as read"""
        self.is_read = True
        self.save(update_fields=['is_read'])

    def get_week_label(self):
        """Get human-readable week label"""
        return f"{self.week_start_date.strftime('%b %d')} - {self.week_end_date.strftime('%b %d, %Y')}"


class DailyBrief(models.Model):
    """
    Daily Pulse / Morning Brief

    Generated every morning and shown to user at login
    Structure based on 6 blocks:
    1. 🕐 Greeting
    2. 🎯 Priorities
    3. 📊 Workload
    4. ⚠️ Warnings/Reminders
    5. 💡 Smart Suggestions
    6. 📈 Weekly Progress
    """
    WORKLOAD_STATUS_CHOICES = [
        ('light', 'Light'),        # 0-40%
        ('optimal', 'Optimal'),    # 40-70%
        ('heavy', 'Heavy'),        # 70-90%
        ('overloaded', 'Overloaded'),  # 90%+
    ]

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='daily_briefs'
    )

    # Date
    date = models.DateField(help_text="Date of this brief")

    # Block 1: 🕐 Greeting
    greeting_message = models.TextField(
        help_text="Personalized greeting based on time of day"
    )

    # Block 2: 🎯 Priorities (top 2-3 tasks)
    top_priorities = models.JSONField(
        default=list,
        help_text="""
        Top priority tasks for today: [
            {
                "task_id": 1,
                "title": "Speaking practice",
                "reason": "high priority + deadline tomorrow",
                "deadline": "2025-10-20",
                "timebox_minutes": 60
            }
        ]
        """
    )

    # Block 3: 📊 Workload
    workload_percentage = models.IntegerField(
        default=0,
        help_text="Percentage of day filled with tasks (0-100+)"
    )
    workload_status = models.CharField(
        max_length=20,
        choices=WORKLOAD_STATUS_CHOICES,
        default='optimal'
    )
    total_timebox_minutes = models.IntegerField(
        default=0,
        help_text="Total minutes of scheduled tasks"
    )
    available_minutes = models.IntegerField(
        default=480,  # 8 hours
        help_text="User's available minutes for the day"
    )

    # Block 4: ⚠️ Warnings/Reminders
    warnings = models.JSONField(
        default=list,
        help_text="""
        Warnings and reminders: [
            {
                "type": "low_progress",
                "category": "study",
                "message": "Учёба 0% прогресса за неделю",
                "severity": "medium"
            },
            {
                "type": "deadline",
                "message": "Интервью с Microsoft завтра в 14:00",
                "severity": "high"
            }
        ]
        """
    )

    # Block 5: 💡 Smart Suggestions
    smart_suggestions = models.JSONField(
        default=list,
        help_text="""
        Smart suggestions: [
            {
                "type": "category_balance",
                "message": "Добавить задачу 'Research CEU requirements'?",
                "action": {
                    "type": "add_task",
                    "title": "Research CEU requirements",
                    "category": "study",
                    "timebox": 30
                }
            },
            {
                "type": "quick_win",
                "message": "У тебя есть 2 quick win задачи (15 мин)",
                "task_ids": [5, 6]
            }
        ]
        """
    )

    # Block 6: 📈 Weekly Progress
    weekly_progress = models.JSONField(
        default=dict,
        help_text="""
        Weekly progress summary: {
            "completion_rate": 72,
            "completed_tasks": 18,
            "total_tasks": 25,
            "overdue_tasks": 2,
            "streak_days": 5
        }
        """
    )

    # Full formatted message
    full_message = models.TextField(
        help_text="Complete formatted brief message for display"
    )

    # Display tracking
    shown_in_push = models.BooleanField(default=False)
    shown_in_app = models.BooleanField(default=False)
    shown_in_chat = models.BooleanField(default=False)
    first_shown_at = models.DateTimeField(null=True, blank=True)

    # Generation metadata
    generated_at = models.DateTimeField(auto_now_add=True)
    regenerated_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="Last time brief was regenerated"
    )
    generation_trigger = models.CharField(
        max_length=20,
        choices=[
            ('scheduled', 'Scheduled (7 AM)'),
            ('on_login', 'On Login'),
            ('manual', 'Manual Request'),
        ],
        default='scheduled'
    )

    class Meta:
        ordering = ['-date']
        indexes = [
            models.Index(fields=['user', '-date']),
            models.Index(fields=['date']),
        ]
        unique_together = ['user', 'date']

    def __str__(self):
        return f"{self.user.email} - {self.date.strftime('%Y-%m-%d')} ({self.workload_status})"

    def mark_shown(self, channel: str):
        """Mark brief as shown in specific channel"""
        if channel == 'push':
            self.shown_in_push = True
        elif channel == 'app':
            self.shown_in_app = True
        elif channel == 'chat':
            self.shown_in_chat = True

        if not self.first_shown_at:
            self.first_shown_at = timezone.now()

        self.save(update_fields=['shown_in_push', 'shown_in_app', 'shown_in_chat', 'first_shown_at'])

    def should_regenerate(self):
        """Check if brief should be regenerated"""
        if not self.regenerated_at:
            return True

        # Regenerate if older than 1 hour
        age = timezone.now() - self.regenerated_at
        return age.total_seconds() > 3600

    def get_workload_emoji(self):
        """Get emoji for workload status"""
        emojis = {
            'light': '😌',
            'optimal': '⚡',
            'heavy': '💪',
            'overloaded': '⚠️'
        }
        return emojis.get(self.workload_status, '📊')
