# Generated by Django 5.2.10 on 2026-02-26 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university_database', '0004_countryrequirement_default_essay_required_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_level', models.CharField(choices=[('global', 'Global'), ('country', 'Country'), ('university', 'University'), ('program', 'Program'), ('scholarship', 'Scholarship')], db_index=True, default='university', max_length=20)),
                ('country', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('track', models.CharField(default='direct', max_length=30)),
                ('intake', models.CharField(blank=True, default='', max_length=30)),
                ('degree_level', models.CharField(blank=True, default='', max_length=30)),
                ('citizenship', models.CharField(blank=True, default='', max_length=50)),
                ('requirement_key', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('required', 'Required - not satisfied'), ('not_required', 'Not applicable'), ('unknown', 'Needs verification'), ('satisfied', 'Requirement met'), ('missing', 'Required but missing')], db_index=True, default='unknown', max_length=20)),
                ('verification_level', models.CharField(choices=[('official', 'Official source'), ('vendor', 'Vendor/uni portal'), ('assumed', 'Country default'), ('user_reported', 'User reported')], db_index=True, default='assumed', max_length=20)),
                ('source_domain_type', models.CharField(blank=True, choices=[('government', 'Government website'), ('university', 'University official portal'), ('vendor', 'Third-party vendor'), ('other', 'Other source')], db_index=True, max_length=20)),
                ('source', models.CharField(choices=[('country_rule', 'Country Requirement Rule'), ('university_rule', 'University Requirement Rule'), ('scholarship_rule', 'Scholarship Requirement Rule'), ('program_rule', 'Program Requirement Rule'), ('manual_override', 'Manually verified')], default='university_rule', max_length=50)),
                ('evidence_fields', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirement_instances', to='university_database.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_instances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scope_level', 'country', 'requirement_key'],
            },
        ),
        migrations.CreateModel(
            name='RequirementPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pack_type', models.CharField(choices=[('country', 'Country Pack'), ('scholarship', 'Scholarship Pack'), ('program', 'Program Pack')], db_index=True, max_length=20)),
                ('requirement_templates', models.JSONField(blank=True, default=list)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['pack_type', '-priority', 'country'],
                'indexes': [models.Index(fields=['pack_type', 'country', 'is_active'], name='requirement_pack_ty_aa93b5_idx')],
            },
        ),
        migrations.CreateModel(
            name='RequirementSourceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('link_url', models.URLField(max_length=500)),
                ('hash_excerpt', models.TextField(blank=True)),
                ('updated_by', models.CharField(choices=[('admin', 'Admin manual update'), ('system', 'System ingestion'), ('user', 'User reported')], default='system', max_length=20)),
                ('is_valid', models.BooleanField(default=True)),
                ('validation_notes', models.TextField(blank=True)),
                ('requirement_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='requirements.requirementinstance')),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='RequirementTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('category', models.CharField(choices=[('visa', 'Visa'), ('medical', 'Medical'), ('docs', 'Documents'), ('finance', 'Finance'), ('apply', 'Application'), ('offer', 'Post-Offer'), ('scholarship', 'Scholarship')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('default_evidence_fields', models.JSONField(blank=True, default=list)),
                ('default_link_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'key'],
                'indexes': [models.Index(fields=['key', 'is_active'], name='requirement_key_7fdb18_idx'), models.Index(fields=['category', 'is_active'], name='requirement_categor_5d33ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='RequirementRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('country', 'Country'), ('university', 'University'), ('scholarship', 'Scholarship'), ('program', 'Program')], db_index=True, max_length=50)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('overrides', models.JSONField(blank=True, default=dict)),
                ('link_url', models.URLField(blank=True)),
                ('priority', models.CharField(choices=[('blocker', 'Blocker - prevents application'), ('warning', 'Warning - can start but need soon'), ('info', 'Information only')], db_index=True, default='info', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirement_rules', to='university_database.university')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='requirements.requirementtemplate')),
            ],
            options={
                'ordering': ['priority', 'scope', 'country'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVaultItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('passport_scan', 'Passport Scan'), ('passport_expiry', 'Passport Expiry Date'), ('ielts_trf', 'IELTS Test Report Form'), ('toefl_score', 'TOEFL Score Report'), ('transcript_pdf', 'Official Transcript'), ('transcript_translation', 'Transcript Translation'), ('bank_statement', 'Bank Statement'), ('tax_certificate', 'Tax Certificate'), ('property_proof', 'Property Ownership Proof'), ('medical_exam', 'Medical Exam Certificate'), ('visa_approval', 'Visa Approval Document'), ('offer_letter', 'University Offer Letter'), ('enrollment_deposit', 'Enrollment Deposit Receipt'), ('cas_document', 'CAS Confirmation Document'), ('i20_document', 'I-20 Form')], db_index=True, max_length=50)),
                ('file_url', models.URLField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('verification_notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_vault', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user', 'doc_type'], name='requirement_user_id_8032f3_idx'), models.Index(fields=['user', 'is_verified'], name='requirement_user_id_0d658c_idx'), models.Index(fields=['-uploaded_at'], name='requirement_uploade_b7d158_idx')],
                'unique_together': {('user', 'doc_type', 'file_name')},
            },
        ),
        migrations.AddIndex(
            model_name='requirementinstance',
            index=models.Index(fields=['user', 'status'], name='requirement_user_id_39d502_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementinstance',
            index=models.Index(fields=['user', 'scope_level'], name='requirement_user_id_d16451_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementinstance',
            index=models.Index(fields=['country', 'requirement_key'], name='requirement_country_c9fbfd_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementinstance',
            index=models.Index(fields=['user', 'verification_level'], name='requirement_user_id_74dbf8_idx'),
        ),
        migrations.AddConstraint(
            model_name='requirementinstance',
            constraint=models.UniqueConstraint(condition=models.Q(('university__isnull', False)), fields=('user', 'university', 'requirement_key', 'track'), name='unique_user_university_requirement'),
        ),
        migrations.AddConstraint(
            model_name='requirementinstance',
            constraint=models.UniqueConstraint(condition=models.Q(('university__isnull', True)), fields=('user', 'country', 'requirement_key', 'track'), name='unique_user_country_requirement'),
        ),
        migrations.AddIndex(
            model_name='requirementsourcesnapshot',
            index=models.Index(fields=['requirement_instance', '-fetched_at'], name='requirement_require_cb2f6c_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementsourcesnapshot',
            index=models.Index(fields=['fetched_at'], name='requirement_fetched_6f1473_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementrule',
            index=models.Index(fields=['scope', 'country', 'is_active'], name='requirement_scope_451918_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementrule',
            index=models.Index(fields=['university', 'is_active'], name='requirement_univers_5b1366_idx'),
        ),
    ]
