# Generated by Django 5.1.5 on 2026-01-26 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Community name (e.g., 'USA Applicants', 'SAT Prep')", max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Community description and purpose')),
                ('community_type', models.CharField(choices=[('region', 'Region'), ('topic', 'Topic')], help_text='Whether this is a region or topic community', max_length=20)),
                ('icon', models.CharField(default='🎓', help_text='Emoji or icon for the community', max_length=10)),
                ('banner_color', models.CharField(default='#5B6AFF', help_text='Hex color for banner', max_length=7)),
                ('rules', models.JSONField(blank=True, default=list, help_text="Community rules: ['No spam', 'Be respectful', ...]")),
                ('member_count', models.IntegerField(default=0, help_text='Cached member count')),
                ('online_count', models.IntegerField(default=0, help_text='Cached online users count')),
                ('post_count', models.IntegerField(default=0, help_text='Cached post count')),
                ('is_official', models.BooleanField(default=False, help_text='Official PathAI community')),
                ('tags', models.JSONField(blank=True, default=list, help_text="Tags for search: ['sat', 'essays', 'ivy-league']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moderators', models.ManyToManyField(blank=True, help_text='Community moderators', related_name='moderated_communities', to=settings.AUTH_USER_MODEL)),
                ('related_communities', models.ManyToManyField(blank=True, help_text='Similar communities users might like', to='community.community')),
            ],
            options={
                'verbose_name_plural': 'Communities',
                'ordering': ['-is_official', '-member_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CommunityMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='member', max_length=20)),
                ('display_name', models.CharField(blank=True, help_text='Optional display name for this community', max_length=100)),
                ('notification_enabled', models.BooleanField(default=True, help_text='Receive notifications from this community')),
                ('last_visited_at', models.DateTimeField(blank=True, help_text='Last time user visited this community', null=True)),
                ('post_count', models.IntegerField(default=0, help_text='Number of posts by user in this community')),
                ('comment_count', models.IntegerField(default=0, help_text='Number of comments by user in this community')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='community.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Community Members',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Post title', max_length=300)),
                ('content', models.TextField(help_text='Post body/content')),
                ('flair', models.CharField(blank=True, choices=[('success', 'SUCCESS'), ('question', 'QUESTION'), ('advice', 'ADVICE'), ('essay', 'ESSAY'), ('news', 'NEWS'), ('resource', 'RESOURCE'), ('discussion', 'DISCUSSION'), ('rant', 'RANT')], help_text='Post flair/tag', max_length=50)),
                ('images', models.JSONField(blank=True, default=list, help_text="List of image URLs: ['https://...', ...]")),
                ('files', models.JSONField(blank=True, default=list, help_text="List of file attachments: [{'url': '...', 'name': '...'}]")),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0, help_text='Cached comment count')),
                ('view_count', models.IntegerField(default=0, help_text='Cached view count')),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned by moderators')),
                ('is_locked', models.BooleanField(default=False, help_text='Comments disabled')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft deleted by user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='community.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Comment text')),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft deleted by user')),
                ('is_edited', models.BooleanField(default=False, help_text='Whether comment has been edited')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.post')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('upvote', 'Upvote'), ('downvote', 'Downvote')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='community.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('upvote', 'Upvote'), ('downvote', 'Downvote')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='community.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['comment', 'vote_type'], name='community_c_comment_fe19ff_idx')],
                'unique_together': {('user', 'comment')},
            },
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['slug'], name='community_c_slug_911dd0_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['community_type'], name='community_c_communi_e477a9_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['-member_count'], name='community_c_member__45677f_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymember',
            index=models.Index(fields=['user', 'community'], name='community_c_user_id_2357be_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymember',
            index=models.Index(fields=['community', '-joined_at'], name='community_c_communi_fa35d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='communitymember',
            unique_together={('user', 'community')},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['community', '-created_at'], name='community_p_communi_9f2052_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', '-created_at'], name='community_p_user_id_49d8d3_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-upvotes'], name='community_p_upvotes_eaba13_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['flair'], name='community_p_flair_87fdaa_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='community_p_created_6febb2_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'created_at'], name='community_c_post_id_bea033_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', '-created_at'], name='community_c_user_id_767aad_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent_comment'], name='community_c_parent__543611_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-upvotes'], name='community_c_upvotes_3f48e2_idx'),
        ),
        migrations.AddIndex(
            model_name='postvote',
            index=models.Index(fields=['post', 'vote_type'], name='community_p_post_id_e720f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postvote',
            unique_together={('user', 'post')},
        ),
    ]
