# Generated by Django 5.1.5 on 2026-01-26 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, help_text='Reason for blocking (optional)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When user was blocked')),
                ('blocked', models.ForeignKey(help_text='User who was blocked', on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(help_text='User who blocked', on_delete=django.db.models.deletion.CASCADE, related_name='blocking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blocked User',
                'verbose_name_plural': 'Blocked Users',
                'indexes': [models.Index(fields=['blocker', '-created_at'], name='social_bloc_blocker_76d01a_idx')],
                'unique_together': {('blocker', 'blocked')},
            },
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Message text content')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of attachments: [{"type": "image", "url": "..."}, {"type": "file", "url": "...", "name": "..."}]')),
                ('is_read', models.BooleanField(default=False, help_text='Whether message has been read by recipient')),
                ('read_at', models.DateTimeField(blank=True, help_text='When message was read', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When message was sent')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(help_text='User who received the message', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, help_text='If this is a reply to another message', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='social.directmessage')),
                ('sender', models.ForeignKey(help_text='User who sent the message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Direct Message',
                'verbose_name_plural': 'Direct Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', 'recipient', '-created_at'], name='social_dire_sender__c25f2c_idx'), models.Index(fields=['recipient', 'is_read', '-created_at'], name='social_dire_recipie_163ea6_idx'), models.Index(fields=['-created_at'], name='social_dire_created_f4fb3c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When follow relationship was created')),
                ('follower', models.ForeignKey(help_text='User who is following', on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(help_text='User being followed', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Follow',
                'verbose_name_plural': 'Follows',
                'indexes': [models.Index(fields=['follower', '-created_at'], name='social_foll_followe_31933d_idx'), models.Index(fields=['following', '-created_at'], name='social_foll_followi_6c5306_idx')],
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
