# Generated by Django 5.1.5 on 2025-10-15 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_preferred_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('study', 'Study'), ('career', 'Career'), ('sport', 'Sport'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(help_text="e.g., 'Get into top CS MS program'", max_length=200)),
                ('constraints', models.JSONField(default=dict, help_text='\n        Goal-specific constraints. Examples:\n        Study: {"country": "USA", "budget": "$10-30k", "degree": "MS CS", "deadline": "2025-12-01"}\n        Career: {"target_role": "Product Manager", "industry": "Fintech", "experience": "3-5 years"}\n        Sport: {"sport_type": "Gym", "goal": "Build muscle", "weekly_hours": 6}\n        ')),
                ('preferences', models.JSONField(default=dict, help_text='\n        User preferences. Examples:\n        Study: {"regions": ["West Coast"], "program_focus": ["AI/ML"], "campus_size": "Large"}\n        Career: {"remote_ok": true, "startup_vs_corporate": "Startup"}\n        ')),
                ('assets', models.JSONField(default=dict, help_text='{"cv_url": "...", "linkedin": "...", "portfolio": "..."}')),
                ('timeline', models.JSONField(default=dict, help_text='{"start_date": "2025-10-15", "target_date": "2026-06-01", "hard_deadlines": [...]}')),
                ('priority_weight', models.FloatField(default=1.0, help_text='Relative priority compared to other goals (0.1-1.0)')),
                ('daily_time_budget_minutes', models.IntegerField(default=120, help_text='Minutes per day user can dedicate to this goal')),
                ('cadence_rules', models.JSONField(blank=True, default=dict, help_text='\n        Study: {"pattern": "shortlist → deadlines → essays → lors → submissions"}\n        Career: {"weekly": {"M": "apply_2", "W": "apply_2", "F": "apply_2", "Tue": "referrals_3", "Thu": "mocks_2"}}\n        Sport: {"daily": {"Mon": "chest", "Tue": "arms", "Wed": "legs", ...}}\n        ')),
                ('is_active', models.BooleanField(default=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goalspecs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority_weight', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='users_goals_user_id_734488_idx'), models.Index(fields=['goal_type'], name='users_goals_goal_ty_010c6a_idx')],
            },
        ),
    ]
