# Generated by Django 5.1.5 on 2025-10-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_goalspec'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalspec',
            name='category',
            field=models.CharField(choices=[('study', 'Study'), ('career', 'Career'), ('sport', 'Sport'), ('finance', 'Finance'), ('language', 'Language'), ('health', 'Health'), ('creative', 'Creative'), ('admin', 'Admin'), ('research', 'Research'), ('networking', 'Networking'), ('travel', 'Travel'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='goalspec',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the goal'),
        ),
        migrations.AddField(
            model_name='goalspec',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, help_text='{"allowDocs": false, "allowEmails": false, "allowCalendar": false}'),
        ),
        migrations.AddField(
            model_name='goalspec',
            name='quick_wins',
            field=models.JSONField(blank=True, default=list, help_text='[{"title": "...", "description": "...", "estimated_time": "..."}]'),
        ),
        migrations.AddField(
            model_name='goalspec',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text='\n        Complete survey data from onboarding.\n        Study: {"country": "USA", "degree": "MSc CS", "budget": "£10-30k", "intake": "Sep 2026", ...}\n        Career: {"targetRole": "PM", "industry": "Fintech", "experience": "3 years", ...}\n        Sport: {"sportType": "Gym", "sportGoal": "Build muscle", "weeklyHours": "6", ...}\n        '),
        ),
        migrations.AddField(
            model_name='goalspec',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='goalspec',
            name='target_date',
            field=models.DateField(blank=True, help_text='Target completion date', null=True),
        ),
        migrations.AlterField(
            model_name='goalspec',
            name='goal_type',
            field=models.CharField(choices=[('study', 'Study'), ('career', 'Career'), ('sport', 'Sport'), ('finance', 'Finance'), ('language', 'Language'), ('health', 'Health'), ('creative', 'Creative'), ('admin', 'Admin'), ('research', 'Research'), ('networking', 'Networking'), ('travel', 'Travel'), ('other', 'Other')], max_length=20),
        ),
    ]
