# Generated by Django 5.1.5 on 2025-10-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_goalspec_category_goalspec_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_available_minutes',
            field=models.IntegerField(default=480, help_text="User's available working minutes per day (default: 480 = 8 hours)"),
        ),
    ]
