# Generated by Django 5.1.5 on 2025-10-19 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_daily_available_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='push_enabled',
            field=models.BooleanField(default=True, help_text='Global push notifications toggle'),
        ),
        migrations.AddField(
            model_name='user',
            name='push_token',
            field=models.CharField(blank=True, help_text='Expo push notification token', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_reminders_enabled', models.BooleanField(default=True, help_text='Reminders before scheduled tasks')),
                ('deadline_notifications_enabled', models.BooleanField(default=True, help_text='Deadline and overdue notifications')),
                ('ai_motivation_enabled', models.BooleanField(default=True, help_text='Motivational messages from AI coach')),
                ('daily_pulse_reminder_enabled', models.BooleanField(default=True, help_text='Daily check-in reminders')),
                ('task_reminder_minutes_before', models.IntegerField(default=15, help_text='How many minutes before task to send reminder')),
                ('daily_pulse_time', models.TimeField(default='20:00', help_text='Time to send daily pulse reminder (e.g., 8 PM)')),
                ('quiet_hours_enabled', models.BooleanField(default=False, help_text='Enable quiet hours (no notifications)')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Quiet hours start time (e.g., 22:00)', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='Quiet hours end time (e.g., 08:00)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preferences',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
    ]
