# Generated by Django 5.1.5 on 2025-11-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_add_conversational_onboarding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='coding_experience',
            field=models.TextField(blank=True, help_text='Programming background and skills for technical programs'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='why_this_field',
            field=models.TextField(blank=True, help_text='Motivation for choosing this field of study'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='target_schools',
            field=models.JSONField(blank=True, default=list, help_text='["University of Edinburgh", "UCL"] from conversational onboarding'),
        ),
    ]
