# Generated by Django 5.1.5 on 2025-11-11 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_userprofile_achievement_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_categories', models.JSONField(default=list, help_text='Categories user selected for onboarding, e.g., ["study", "career"]')),
                ('completed_categories', models.JSONField(default=list, help_text='Categories where user has completed chat, e.g., ["study"]')),
                ('current_category', models.CharField(blank=True, help_text='Category user is currently chatting for, e.g., "study"', max_length=50)),
                ('status', models.CharField(choices=[('category_selection', 'Selecting Categories'), ('chatting', 'Chatting for Categories'), ('generating_tasks', 'Generating Tasks'), ('complete', 'Complete')], default='category_selection', help_text='Current onboarding stage', max_length=50)),
                ('is_complete', models.BooleanField(default=False, help_text='True when all categories are complete and tasks are generated')),
                ('tasks_generated', models.BooleanField(default=False, help_text='True when tasks have been generated (idempotency check)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When onboarding fully completed', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Onboarding Progress',
                'verbose_name_plural': 'Onboarding Progress',
            },
        ),
        migrations.CreateModel(
            name='OnboardingChatData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Category this data is for, e.g., "study", "career", "sport"', max_length=50)),
                ('extracted_data', models.JSONField(default=dict, help_text='Extracted data from conversational onboarding for this category')),
                ('is_merged', models.BooleanField(default=False, help_text='True when data has been merged into UserProfile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_chat_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Onboarding Chat Data',
                'verbose_name_plural': 'Onboarding Chat Data',
                'unique_together': {('user', 'category')},
            },
        ),
    ]
