# Generated by Django 5.1.5 on 2025-11-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_userprofile_llm_budget_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='courses_certifications',
            field=models.JSONField(blank=True, default=list, help_text='["AWS Certified Solutions Architect", "CS50", "Stanford Machine Learning"]'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education_background',
            field=models.JSONField(blank=True, default=list, help_text='[{"degree": "BS Computer Science", "institution": "Stanford University", "year": "2020", "gpa": "3.8"}]'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='projects',
            field=models.JSONField(blank=True, default=list, help_text='[{"name": "E-commerce Platform", "description": "Full-stack app", "metrics": "50k users", "tech_stack": ["React", "Node.js"]}]'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_history',
            field=models.JSONField(blank=True, default=list, help_text='[{"company": "Google", "role": "Software Engineer", "duration": "2020-2023", "description": "Built scalable systems"}]'),
        ),
    ]
