# Generated by Django 5.1.5 on 2026-01-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_enhanced_career_data_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, help_text="URL to user's profile picture (from OAuth or custom)"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, help_text='Display name for the user (from OAuth or custom)', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='provider',
            field=models.CharField(blank=True, help_text="OAuth provider: 'google', 'apple', or None for email/password", max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='provider_id',
            field=models.CharField(blank=True, help_text='Unique ID from OAuth provider (e.g., Google sub, Apple sub)', max_length=255, null=True, unique=True),
        ),
    ]
