# Generated by Django 5.1.5 on 2026-01-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_userprofile_avatar_url_userprofile_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('followers', 'Followers Only'), ('private', 'Private')], default='public', help_text='Who can see user activity (posts, comments, etc.)', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio about the user (max 500 chars)', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='follower_count',
            field=models.IntegerField(default=0, help_text='Cached follower count'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='following_count',
            field=models.IntegerField(default=0, help_text='Cached following count'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gpa_public',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Public GPA (only shown if stats_visibility allows)', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ielts_score_public',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Public IELTS score (only shown if stats_visibility allows)', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, help_text="User's location (city, country)", max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='message_privacy',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('followers', 'Followers Only'), ('following', 'Following Only')], default='everyone', help_text='Who can send direct messages', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='post_count',
            field=models.IntegerField(default=0, help_text='Cached post count across communities'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sat_score_public',
            field=models.IntegerField(blank=True, help_text='Public SAT score (only shown if stats_visibility allows)', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stats_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('followers', 'Followers Only'), ('private', 'Private')], default='public', help_text='Who can see academic stats (GPA, SAT, etc.)', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_universities',
            field=models.JSONField(blank=True, default=list, help_text='List of target universities: ["Harvard", "MIT", "Stanford"]'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_likes',
            field=models.IntegerField(default=0, help_text='Cached total upvotes received on posts/comments'),
        ),
    ]
