# Generated by Django 5.2.10 on 2026-03-15 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_userprofile_activity_visibility_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='intervention_history',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_intervention_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_intervention_type',
        ),
    ]
